flyingcircusio/nixpkgs

nixos/modules/flyingcircus/lib/files.nix
nixos/modules/flyingcircus/platform/default.nix
nixos/modules/flyingcircus/platform/logrotate/default.nix
nixos/modules/flyingcircus/platform/systemd.nix
nixos/modules/flyingcircus/platform/user.nix

a) provide /etc/local/systemd where service users can place
arbitrary unit files that will be merged with ``fc-manage``
b) revamp the logrotate integration. every user gets his own
timer that explicitly changes to the user in the service config
instead of being injected into the systemd user instance.
c) no lingering, no loitering, no littering.

Fix systemd user unit management so that users can place own unit files in /etc/local/systemd (#20984)

---

nixos/modules/flyingcircus/roles/mongodb/default.nix

It does not make sense to artifically limit mongodb (files -> allows connections)

increase mongo resource limits

---

nixos/modules/config/swap.nix
nixos/modules/flyingcircus/vagrant-provision.nix

fallocate creates a sparse file which is not suiteable for swap (at least with the XFS version which is running). Thus never use it, but use dd.
re #21522

provide swapfiles for vagant

---

nixos/modules/flyingcircus/files/etc_nixos_local.nix

The whole ENC thingy is not so relevant on the platform. Thus remove it. temporariliy adding packages is a more common.

simplify local.nix for new nodes

---

nixos/modules/flyingcircus/platform/user.nix

This is the way I understand https://flyingcircus.io/doc/guide/platform_nixos/base.html#interaction
This is a rather broad rule. But since users can just put in systemd units and run them as root it's not much of a difference, is it.
re #22013

Allow generic systemctl calls for service users (not only systemctl fc-manage) (#22013)

---

nixos/modules/flyingcircus/services/sensu/client.nix

This allows sensuclient to interact with services more easily. This especially helps to check supervisor with a group-writable socket.
Also change some arbitrary white-space to trigger a restart of sensuclient.

Add sensuclient user to services group.

---

nixos/modules/flyingcircus/platform/default.nix
nixos/modules/flyingcircus/platform/systemd.nix

I think there is not much of a point to hide journal messages from some
users. Make them readable by anyone.
Also restructured platform/default.nix vs. platform/systemd.nix a bit so
I hope it will be easier to find certain stuff in the future.
Fixes #22577

Make systemd journal world-readable (#22577)

---

nixos/modules/flyingcircus/platform/default.nix
nixos/modules/flyingcircus/platform/packages.nix
nixos/modules/flyingcircus/roles/webproxy.nix

re #21977
changelog: Add webproxy role for nixos (varnish, #21977)

Match default configuration of varnish tools (varnishstat, varnishlog, etc.) with VSM location so that they work out of the box (#21977)

---

nixos/modules/flyingcircus/packages/default.nix
nixos/modules/flyingcircus/packages/postfix/3.0.nix
nixos/modules/flyingcircus/packages/postfix/post-install-script.patch
nixos/modules/flyingcircus/packages/postfix/postfix-3.0-no-warnings.patch
nixos/modules/flyingcircus/packages/postfix/postfix-script-shell.patch
nixos/modules/flyingcircus/packages/postfix/relative-symlinks.patch
nixos/modules/flyingcircus/roles/mailserver.nix
nixos/release-flyingcircus.nix

This pull request extends the mailserver role to allow contributing a custom local.cf to postfix as well as adding a canonical.pcre file for e.g. redirecting mails. Also it updates the used Postfix to 3.0.3

Update Postfix to 3.0.3 and extend mailserver role for custom local.cf and canonical.pcre 

---

nixos/modules/flyingcircus/roles/mailserver.nix

This PR allows service users to set myhostname via /etc/local/postfix/myhostname

Using /etc/local/postfix/myhostname to configure myhostname on Postfix' main.cf (#23084)

---

nixos/modules/flyingcircus/roles/redis.nix

This PR fixes a few warnings popped up during startup of Redis: 
- Increase of allowed file descriptors 
- Disable Transparent Huge Pages

23179 fix redis warnings

---

nixos/modules/flyingcircus/roles/redis.nix

Also this ensures both, redis as well as group service have permission for rw on that file. 
Re #23116

Ensure /etc/local/redis/password is owned by redis:service (#23116)

---

nixos/modules/flyingcircus/services/sensu/client.nix

In contrast to what #23143 says the load is already relative to CPUs (-r flag).
Changelog: none necessary (I think)
re #23143

increase expected load to the values from the gentoo world.

---

nixos/modules/flyingcircus/roles/mailserver.nix
nixos/modules/services/mail/postfix.nix

changelog: Postfix: Fix setting of IPv6 addresses in mynetworks (#23236)
Also set data-dir to /var/postfix as all the other files. If /var/lib/postfix is not there already startup fails otherwise. The path/behaviour might have chaned with the update to 3.0 and we did not set up a new postfix since then.
re #23236

Postfix: Fix setting of IPv6 addresses in mynetworks (#23236)

---

nixos/modules/flyingcircus/lib/network.nix
nixos/modules/flyingcircus/roles/webproxy.nix

Changelog: Varnish listens on SRV as well now. Before it was only listening on 127.0.0.1 (#23196)
Impact: Varnish will be restarted.
re #23196

Varnish listens on ethsrv as well now. Before it was only listening on 127.0.0.1. (#23196)

---

nixos/modules/flyingcircus/platform/network.nix

re #23464
changelog: Fix resolving IP addresses from /etc/hosts entries for hosts with more than one IP address (#23464).

resolve multiple ips for one host from /etc/hosts

---

nixos/modules/flyingcircus/packages/fcmanage/default.nix
nixos/modules/flyingcircus/packages/fcmanage/fc/manage/dmi_memory.py
nixos/modules/flyingcircus/packages/fcmanage/fc/manage/tests/dmidecode_multibank.out
nixos/modules/flyingcircus/packages/fcmanage/fc/manage/tests/test_dmi_memory.py
nixos/modules/flyingcircus/packages/fcmanage/setup.py

re #23358
Changelog: Fix maintenance handling for VMs with RAM a amount which is not a power of 2 (#23358)

fix DMI memory computation when there is more than one memory bank

---

nixos/modules/flyingcircus/roles/mailserver.nix

The readme says `main.cf` and that makes sense. It could happen we would like to customize `master.cf` in the future. A `local.cf` would be pretty stupid then.
re #23458
changelog: Fix postfix' local customization filename to `main.cf` (#23458)
impact: If you have customized postfix with a `/etc/local/postfix/local.cf` copy it over to `/etc/local/postfix/main.cf` before the release. You ran remove `local.cf` after the release. Be sure to also change automatic deployment procedures accordingly.

fix postfix local modifications file name

---

nixos/modules/flyingcircus/platform/network.nix

Raise TCP challenge ACK limit. This workaround can be reversed once
Linux 4.7 is in production.
Fixes #23260

Security: disable TCP challenge ACK limit (CVE-2016-5696, #23260)

---

pkgs/development/libraries/gnutls/generic.nix
pkgs/development/libraries/libtasn1/default.nix

This PR updates libtasn 4.7 -> 4.8 which is closing CVE-2016-4008
Re #23926

Update libtasn 4.7 -> 4.8

---

pkgs/development/libraries/gnutls/generic.nix
pkgs/development/libraries/libidn/default.nix

This PR updates libidn 1.32 -> 1.33. This will fix various CVE.
Re 23893

Update libidn 1.32 -> 1.33

---

nixos/modules/flyingcircus/infrastructure/fcio/default.nix

At 0 we do not see kernel dumps on the serial console when it's not absolutely
a panic. We've seen VMs that were in a semi-usable state, probably due to
some storage issue, but it's unclear whether Ceph or XFS was at fault.
I'm betting the kernel is saying _something_ but we can't see it.

Increase kernel loglevel to 4.

---

pkgs/tools/networking/dd-agent/default.nix

Changelog: Add mysql support for DataDog agent. This allows to monitor MySQL with DataDog.

need pymysql for monitoring mysql.

---

nixos/modules/flyingcircus/roles/mysql.nix

Impact: MySQL servers running on NixOS are being restarted. 
Changelog: Reduce MySQL buffer pool from 80% to 70% of RAM. We saw VMs starting to swap and reduce the buffer pool accordingly.

reduce percona buffer pool to 70% of RAM

---

nixos/modules/flyingcircus/packages/rabbitmq_delayed_message_exchange.nix
nixos/modules/services/amqp/rabbitmq.nix
pkgs/servers/amqp/rabbitmq-server/default.nix

Changelog: Update RabbitMQ to 3.6.5 (#23773)
Impact: RabbitMQ will be restarted.
re #23773

23773 update rabbitmq

---

.github/PULL_REQUEST_TEMPLATE
nixos/modules/flyingcircus/packages/fcmanage/default.nix
nixos/modules/flyingcircus/packages/fcmanage/fc/manage/manage.py
nixos/modules/flyingcircus/packages/fcmanage/setup.py

To activate you need to create /etc/local/build-with-maintenance. If the channel changes a maintenance will be created and the update will be done during the maintenance.
I don't want to activate it unconditionally, yet. The exact behavior and communication will need tweaking and we don't want to push out too many emails to clients w/o use.
no changelog, yet. dark-launch

channel update with maintenance management

---

nixos/modules/flyingcircus/services/sensu/client.nix

This removes the concurrent users check from sensu as customer might have interest on having 5 or 10 or more users logged in and the check only caused noise in such cases. 
Re #22541

Remove check for concurrent users from sensu.

---

nixos/modules/flyingcircus/packages/default.nix
nixos/modules/flyingcircus/packages/dnsmasq.nix
nixos/modules/flyingcircus/platform/packages.nix
nixos/modules/flyingcircus/roles/external_net/vxlan.nix

Impact:
Changelog: Security update for dnsmasq (CVE-2015-8899, #23865).
Updating dnsmasq to 2.76.
CVE-2015-8899
Fixes #23865

Security update for dnsmasq

---

nixos/modules/flyingcircus/packages/default.nix
nixos/modules/flyingcircus/packages/fcmanage/fc/manage/resize.py
nixos/modules/flyingcircus/packages/linux-4.4.nix
nixos/modules/flyingcircus/platform/default.nix
nixos/modules/flyingcircus/platform/packages.nix
pkgs/os-specific/linux/kernel/common-config.nix

Impact: All NixOS VMs will be rebooted due to a kernel update (4.4.27) to fix the "Dirty Cow" security issue.
Changelog:
* Update Linux kernel to 4.4.27
* Automatically detect kernel changes and schedule maintenance for reboots to activate them.

24271 dirty cow linux 4.4.27

---

nixos/modules/flyingcircus/platform/user.nix
nixos/modules/flyingcircus/services/sensu/client.nix
nixos/modules/flyingcircus/static/default.nix

Impact: gids of already existing groups **aren't** changed. A warning conveys this fact. Needs a rebuilt of the Image
Changelog: gids of users/static.nix are respected.
re #21537

moved gids to static/user.nix, fixed the gid ordering

---

nixos/modules/flyingcircus/infrastructure/fcio/collectd.nix

Impact:
It's quite useles to have 5s interval for uptime and it wastes space and bandwidth.

collectd uptime every 5 minutes instead every 5 seconds

---

nixos/modules/flyingcircus/packages/fcsensuplugins/fc/sensuplugins/journal.py
nixos/modules/flyingcircus/services/fcmanage.nix
nixos/modules/flyingcircus/services/sensu/check_journal.yaml
nixos/modules/flyingcircus/services/sensu/client.nix

I think that `journalctl -o json` has a broken output encoding. Instead
of trying to make up a baroque work-around, I'd better revert to plain
text output. `journalctl -o short` preserves UTF-8 encoded special
characters perfectly.
Reduce noisiness by adding `warning: not applying GID change of group
...` to the exclude list.
Also improve check_journal.py sources:
- Do not compile each regexp for each log line -- this is in O(n²).
- Fix spawned journalctl to UTF-8 and decode accordingly.
- Report full log lines including time stamp.
- Refactor repeated code parts in find_hits().
Re #23128
Impact:
Changelog: Fix encoding issues in journal check to reduce false positives (#23128)

Fix check_journal encoding issue

---

nixos/modules/flyingcircus/platform/default.nix
nixos/modules/flyingcircus/platform/user.nix
nixos/modules/flyingcircus/roles/nfs.nix
nixos/modules/flyingcircus/static/default.nix

Set up systemd automount units for each human user if a NFS box server
exists. Also create links from users' home directories for convenient
access.
This is only the first half (`box` client still missing), but valuable in its own.
Re #21486
Impact:
Changelog: Provide NFS box access for NixOS VMs, too.

Box automounts

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/pcre.nix

Impact: A restart of most services will be required due to the widespread usage of pcre
Changelog: Update pcre to 8.39, fixing CVE-2016-3191 (#24063)

Update pcre to 8.39, fixing CVE-2013-0340 (#24063)

---

nixos/modules/flyingcircus/services/sensu/check_journal.yaml

Aim of this PR is to don't trigger the sensu journal check in for SSH errors like 
`error: maximum authentication attempts exceeded for root from <someip> port 55373 ssh2 [preauth]`
Re #25476

Ignore ssh error about maximum authentication attempts at journal check

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/libidn.nix
pkgs/development/libraries/libidn/default.nix

Impact: None
Changelog: refactored libidn to fit our new package structure
re #23893

23893 libidn cve

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/nodejs6/default.nix
nixos/modules/flyingcircus/packages/openssl/1.0.1-cygwin64.patch
nixos/modules/flyingcircus/packages/openssl/darwin-arch.patch
nixos/modules/flyingcircus/packages/openssl/default.nix
nixos/modules/flyingcircus/packages/openssl/use-etc-ssl-certs.patch
nixos/modules/flyingcircus/packages/percona/5.6.nix
nixos/modules/flyingcircus/packages/percona/5.7.nix
nixos/modules/flyingcircus/platform/packages.nix
nixos/modules/flyingcircus/tests/default.nix
nixos/modules/flyingcircus/tests/nodejs6.nix

Impact: All services will need a restart to update OpenSSL.
Changelog: 
* Updating OpenSSL from 1.0.1 to 1.0.2 as 1.0.1 support has ended.  (#23921)
* Fix NodeJS6 to user OpenSSL 1.0.2, which enables SSL-use (#25440)

Update openssl to 1.0.2 and fix nodejs

---

nixos/modules/flyingcircus/roles/loghost.nix
nixos/modules/flyingcircus/static/default.nix

Impact: 
- graylog role starts successfully (most of the time)
- bug: logrotate sometimes fails, as mongodbs reload times out 
Changelog:
re #22495

little fixes to make graylog2 role working again

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/php/default.nix
nixos/modules/flyingcircus/packages/php/fix-paths-php7.patch
nixos/modules/flyingcircus/packages/php/fix-paths.patch

Impact: PHP applications will be restarted.
Changelog: PHP: Use MySQL native driver, which supports several functions not available before (see http://php.net/manual/en/mysqlnd.overview.php for details)

use mysqlnd driver in PHP

---

nixos/modules/services/monitoring/dd-agent.nix

It is logging to files already. Also there are quite some useless error messages which fill up the logs.
re #25713
Impact:
Changelog: Datadog logs only to logfiles, not to journal anymore (#25713)
Note: The service is already customized by us, hence this change doesn't make much of a difference anymore. I plan to update the datadog package and susequently the service later. This will result in a copy in our space and a revert of the upstream service. But I first want to update the client to our main production branch.

don’t have datalog log to syslog/journal

---

nixos/modules/flyingcircus/services/sensu/check_journal.yaml

The PR hides error/warning about disconnects e.g. due to auth fail from journal check. 
Re #25884

Ignore error/warning for disconnects at SSH

---

nixos/modules/flyingcircus/platform/default.nix
nixos/modules/flyingcircus/roles/loghost.nix
nixos/modules/flyingcircus/services/graylog.nix

Impact: 
- nixos.tests.flyingcircus.elasticsearch is working again
Changelog:
- added some default values in platform/default.nix's FCIO* variables.
- FCIO variables are only exported, if ENC data is present.
re #22495

22495 import logstash fixed

---

nixos/modules/flyingcircus/packages/fcmanage/fc/manage/manage.py

If the “next” configuration was not activated, the channel “next” would still be there. This made that there never was an update any more. We now rely on the maintenance feature to ignore new requests when there is the same already.
Impact: none

Fix activating "next" channel

---

nixos/modules/flyingcircus/roles/loghost.nix
nixos/modules/flyingcircus/static/default.nix

- graylog listens on lo, port 9001
- nginx on srv, port 9000, access allowed only by directory
- added directory proxy ips to static/default.nix
re #22495

put graylog behind a proxy

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/postgresql/default.nix
nixos/modules/flyingcircus/packages/postgresql/disable-resolve_symlinks-94.patch
nixos/modules/flyingcircus/packages/postgresql/disable-resolve_symlinks.patch
nixos/modules/flyingcircus/packages/postgresql/hardcode-pgxs-path-96.patch
nixos/modules/flyingcircus/packages/postgresql/hardcode-pgxs-path.patch
nixos/modules/flyingcircus/packages/postgresql/jdbc/default.nix
nixos/modules/flyingcircus/packages/postgresql/less-is-more-96.patch
nixos/modules/flyingcircus/packages/postgresql/less-is-more.patch
nixos/modules/flyingcircus/packages/postgresql/psqlodbc/default.nix
nixos/modules/flyingcircus/packages/postgresql/rum/default.nix
nixos/modules/flyingcircus/packages/postgresql/specify_pkglibdir_at_runtime.patch
nixos/modules/flyingcircus/platform/packages.nix
nixos/modules/flyingcircus/roles/postgresql.nix
nixos/modules/flyingcircus/tests/default.nix
nixos/modules/flyingcircus/tests/postgresql.nix

- support for the postgresql rum extension
- extended the postgresql test for rum
- only enabled it for postgres >= 9.6
- all-packages.nix is easier to play with: nix-shell -I nixpkgs=. nixos/modules/flyingcircus/packages/all-packages.nix -A <some_pkg>
Impact:
Changelog:
re #25926

updated postgres to 9.6

---

nixos/modules/flyingcircus/roles/mysql.nix
nixos/modules/flyingcircus/tests/default.nix
nixos/modules/flyingcircus/tests/mysql.nix

The original mysql role is gone. Manual work for every instance running nixos/mysql is required during/after release.
re #26125
Impact:
Changelog: Display selected mysql version (mysql55, mysql56, mysql57) in my.flyingcircus.io.

Provide directory selectable mysql version via mysql55/56/57 roles.

---

nixos/modules/flyingcircus/roles/elasticsearch.nix

The `mkPlatform` call makes the Limit settings vanish. It appears that, *if* someebody needs the mkPlatform there it must go to each element inside the mapping.
re #26125
Impact: ElasticSearch instances will be restarted
Changelog: Fix Elasticsearch resource limits (#26125)

Fix ES resource limits

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/roles/loghost.nix
nixos/modules/flyingcircus/roles/mongodb/default.nix
nixos/modules/flyingcircus/tests/mongodb/default.nix

I explicitly removed the mongodb role itself. This way rebuild will fail and one can decide which role to choose. There are different branches which provide 3.0 or 3.2.
re #26125
Impact:
Changelog: In addition to MongoDB 3.2 we also provide 3.0.

Create separate roles for mongodb 3.0 and 3.2

---

nixos/modules/flyingcircus/infrastructure/fcio/collectd.nix
nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/collectdproxy/README.txt
nixos/modules/flyingcircus/packages/collectdproxy/default.nix
nixos/modules/flyingcircus/packages/collectdproxy/setup.py
nixos/modules/flyingcircus/packages/collectdproxy/src/collectdproxy/location.py
nixos/modules/flyingcircus/packages/collectdproxy/src/collectdproxy/statshost.py
nixos/modules/flyingcircus/roles/statshost.nix
nixos/modules/flyingcircus/services/collectdproxy.nix
nixos/modules/flyingcircus/services/default.nix
nixos/modules/services/monitoring/collectd.nix

The idea is to aggregate data per location, and to compress it before sending it over the wire. Compressing saves about 9/10 of bandwidth here.
Currently collectd is configured to send to both stats.flyingcircus.io and a local proxy. This wasy we can see how much resources the compression requires before actually putting it into production. Luckly influxdb depulicates the data for the case that we get it twice.
NOTE: This is supposed to do nothing until stathostproxy is available in a location. First I'd like to see how it behaves in DEV.
Impact: 
Changelog: none.

Create a proxy for collectd data which compresses

---

nixos/modules/flyingcircus/services/sensu/check_journal.yaml

On our platform there is no need to show this warning and therefore it's only noise inside monitoring. 
Re #26285

Don't report "Disconnecting: Too many authentication failures [preauth]" as a warning inside journal check

---

nixos/modules/flyingcircus/services/sensu/server.nix

`OnUnitActiveSec` only becomes effective if the unit was started once. Using `OnStartupSec` to trigger the initial run.
Impact: none

actually start sensu timer.

---

nixos/modules/flyingcircus/roles/memcached.nix

- check-memcached-stats.rb does not accept multiple, comma-separated addresses as argument to "-h".
- Reflect locally changed port number in the check.
Fixes #26303
Impact:
Changelog: Fix memcached monitoring so that locally changed ports are automatically picked up.

Fix memcached check

---

nixos/modules/flyingcircus/roles/nfs.nix

There is no point in fsck'ing NFS mounts and systemd-fstab-generator
is complaining.
Fixes #26163
Impact:

Disable fsck flag for NFS mounts

---

nixos/modules/flyingcircus/packages/fcsensuplugins/fc/sensuplugins/journal.py

seems to indicate "nothing to show" in more cases.
Impact:
-
Changelog:
Fix edge case on Sensu journal check to avoid spurious errors.

Add another edge case where journalctl might return exit code 1 which

---

nixos/modules/flyingcircus/packages/mongodb/default.nix

This includes several bugfixes, especially segfaults.
Impact:
* MongoDB will be restarted.
Changelog:
* Update MongoDB 3.2 to newest release in series (3.2.12) to benefit from fixes for segfaults and other bugs.

Upgrade MongoDB 3.2 to newest revision in series.

---

nixos/modules/flyingcircus/roles/mailserver.nix

This PR adds opportunity to add custom master.cf content to Postfix via /etc/local/postfix/master.cf. 
Re #26492

Add a way to add custom master.cf content to postfix

---

nixos/modules/flyingcircus/services/default.nix
nixos/modules/flyingcircus/services/sysstat.nix

re #26608
Add a sysstat service (from upstream) to be enabled if required. Further needs and discussions in #26671. This should be merged so we can manually enable the service when required.
Impact:
Changelog: Add sysstat service to be enabled on request.

Add sysstat service

---

nixos/modules/services/monitoring/dd-agent.nix

This would mount the volumes and is completely unnecessary.
Note: the dd-agent service is customized already. I’m continuing that. We probably want to move the service to our part though.
Impact:
Changelog: Exclude autofs from datadog's filesystem checks.

exclude autofs for datadog checks.

---

nixos/modules/flyingcircus/roles/redis.nix
nixos/modules/tasks/network-interfaces-scripted.nix

Impact: - 
Changelog: Fix network bug which caused PostgreSQL/Redis failures during VM startup.
Re #22431

Delay PostgreSQL/Redis startup until DAD is complete

---

nixos/modules/flyingcircus/infrastructure/fcio/default.nix
nixos/modules/flyingcircus/infrastructure/fcio/modprobe.conf

We can't prove that this does anything useful, but we bashed our heads for
about 30 minutes trying to provoke a watchdog reboot. Unfortunately, the
kexec mechanism that is in place usually catches all issues we can provoke
faster than the watchdog. In general this is good news because that means
we have multiple safety nets. In practice we can only show that the module
now loads and that systemd is picking it up.
Fixes #23942
Impact:
Changelog:

Unblacklist the i6300esb module to allow the watchdog to work.

---

nixos/modules/flyingcircus/services/sensu/client.nix

Impact:
Restarts sensu client
Changelog:
The sensu client now has a configurable loglevel so we can customize it locally to aid debugging.

The sensu client now has a configurable loglevel so we can customize it

---

nixos/modules/flyingcircus/roles/loghost.nix
nixos/modules/flyingcircus/services/graylog.nix

To do so you
* add the ES role to the loghost VM
* set the cluster name to “graylog” on any other ES VM in the RG.
re #26893
Impact: Graylog and ElasticSearch instances will be restarted, if there is a Graylog in the project.
Changelog: Allow to add ElasticSearch nodes to the graylog cluster.

Allow to add ES nodes to the graylog cluster.

---

nixos/modules/flyingcircus/packages/nodejs/default.nix
nixos/modules/flyingcircus/tests/default.nix
nixos/modules/flyingcircus/tests/nodejs4.nix

This PR updates NodeJS4 to latest maintenance release inside: 4.8.3. It also adds a simple test for NodeJS service. 
Impact:
Changelog:
Update NodeJS4 to 4.8.3

26455 update nodejs4

---

nixos/modules/flyingcircus/roles/external_net/openvpn.nix

This PR prevents passwords from being printed into output of sensu check when checking whether openvpn is working. 
Re #26899

Don't show passwords inside openvpn check output in sensu

---

nixos/modules/flyingcircus/packages/postgresql/default.nix

This PR updates PostgreSQL from 9.5.1 to 9.5.7 
Re #27035
Impact:
* Postgres 9.5 servers needs to be restarted
* Some indexes might needs to be recalculated. See
*  https://www.postgresql.org/docs/9.5/static/release-9-5-2.html
* https://www.postgresql.org/docs/9.5/static/release-9-5-6.html

Update PostgreSQL 9.5.1 -> 9.5.7

---

nixos/modules/flyingcircus/packages/postgresql/default.nix

This PR will update PostgreSQL 9.4.x to 9.4.12. 
Impact:
* Postgres server needs to be restarted
* Some indexes might needs to be recalculated
Changelog:

Update Postgres 9.4.6 -> 9.4.12

---

nixos/modules/flyingcircus/packages/postgresql/default.nix

This PR updates PostgreSQL 9.6.x to 9.6.3
Impact:
* PostgreSQL 9.6.x servers needs to be restarted
* Some indexes needs to be recalculated
Changelog:
Re #27186

Update PostgreSQL 9.6.1 -> 9.6.3

---

nixos/modules/flyingcircus/platform/network.nix
nixos/modules/flyingcircus/roles/external_net/default.nix
nixos/modules/flyingcircus/roles/external_net/openvpn.nix
nixos/modules/flyingcircus/roles/external_net/vxlan.nix

We have seen DNS amplification attacks because dnsmasq on external
network gateways used to respond to recursive queries on FE. dnsmasq has
been opened on FE originally to server DNS queries coming from OpenVPN
clients.
Now functionality has been separated: dnsmasq acts as recursive resolver
on nx0 and tap0 (or whatever OpenVPN likes to name its local interface),
but acts as authoritative nameserver on the FE address (declines
recursive queries).
To achieve this, we create a new NixOS config option `frontendName`
which points to the FQDN of the public FE interface. dnsmasq is
configured in authoritative mode on this interfaces while declining
recursive DNS and DHCP queries generally on ethfe and ethsto. A Python
snippet wrapped in a derivation performs the necessary address
computations. …

dnsmasq: discern authoritative and resolver roles

---

nixos/modules/flyingcircus/packages/fcsensuplugins/fc/sensuplugins/journalfile.py
nixos/modules/flyingcircus/packages/fcsensuplugins/setup.py
nixos/modules/flyingcircus/services/sensu/client.nix

- changed from one single journal file to all *.journal files under /var/log/journal
- SimpleContext is less verbose through ignoring performance data.
Impact: @ckauhaus Please have a look at SimpleContext and Check, merci
Changelog:
re #26959

add a size check for the system.journal log file

---

nixos/modules/flyingcircus/platform/default.nix
nixos/modules/flyingcircus/platform/packages.nix
nixos/modules/flyingcircus/platform/shell.nix

Also prefix LIBRARY_PATH, PKG_CONFIG_PATH and various include paths
with the appropriate user env directories. Thus, packages installed
locally via nix-env or similar tools always take precendence.
Add some commonly used build tools that operate entirely on the call
level, i.e. they do not add link level dependencies to target programs.
Re #25410
Impact: Users should restart all applications to detect link-level errors.
Changelog: Remove LD_LIBRARY_PATH from default environment. It causes more harm than good (#25410).

Remove LD_LIBRARY_PATH from default environment

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/busybox/busybox-in-store.patch
nixos/modules/flyingcircus/packages/busybox/default.nix

Impact: changed the busybox version within the upstream directory as it's outside the regular packages scope
Changelog: 
re #26962

updates busybox to 1.26

---

nixos/modules/flyingcircus/packages/php-packages.nix

This allows to install global XCache for php5.6 via phpPackages.xcache
Re #27595

Port XCache 3.2.0 to PHP 5.6

---

nixos/modules/flyingcircus/tests/default.nix
nixos/modules/flyingcircus/tests/pdftk.nix

This PR adds a minimalistic test for pdftk to ensure it's getting build on our hydra 
Re #27590

Prebuild pdftk dependencies

---

nixos/modules/flyingcircus/packages/fcsensuplugins/fc/sensuplugins/journalfile.py

Impact: fixes a  race condition, that files moved away which invalidated ```os.path.getsize(file)```
Changelog:
re #27697

moved the globbing right before iterating the list of journal files

---

nixos/modules/flyingcircus/roles/datadog.nix

It needs an apikey to activate which you could only set when it was activated.
Impact:
Changelog: Fix activation of the  Datadog role.

fix dd role-activation

---

nixos/modules/flyingcircus/packages/coturn/default.nix

This PR updates coturn to a more recent version
Re #27762
Impact: coturn-services will be restarted
Changelog: Update coturn from 4.5.0.3 to 4.5.0.6

Update coturn 4.5.0.3 -> 4.5.0.6

---

nixos/modules/flyingcircus/infrastructure/fcio/collectd.nix
nixos/modules/flyingcircus/infrastructure/fcio/default.nix
nixos/modules/flyingcircus/infrastructure/fcio/telegraf.nix
nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/collectd/default.nix
nixos/modules/flyingcircus/roles/elasticsearch.nix
nixos/modules/flyingcircus/roles/mongodb/default.nix
nixos/modules/flyingcircus/roles/mysql.nix
nixos/modules/flyingcircus/roles/nginx.nix
nixos/modules/flyingcircus/roles/postgresql.nix
nixos/modules/flyingcircus/roles/statshost.nix
nixos/modules/flyingcircus/services/default.nix
nixos/modules/flyingcircus/services/grafana.nix
nixos/modules/flyingcircus/services/prometheus/default.nix
nixos/modules/flyingcircus/services/telegraf.nix
nixos/modules/flyingcircus/static/default.nix
nixos/modules/flyingcircus/tests/mariadb.nix
nixos/modules/flyingcircus/tests/postgresql.nix

Impact:
Changelog: Add roles for customer-specific Grafana and Prometheus, to access system metrics. (#27132)
Changelog: Update collectd to 5.7.2 (#27132)
Changelog: Use Telegraf to gather additional system metrics. Telegraf will replace collectd in a  subsequent release. (#27132)

27132 grafana prometheus

---

nixos/modules/flyingcircus/packages/nodejs/default.nix

This PR updates our supported NodeJS-packages to latest upstream release to address CVE-2017-1000381
Impact: NodeJS-services needs to be restarted
Changelog:
Update NodeJS 7.10.0 to 7.10.1, 6.9.1 to 6.11.1 and 4.8.3 to 4.8.4
Re #27817

27817 nodejs security update

---

nixos/modules/flyingcircus/roles/webproxy.nix

Impact: let varnish wait to network.target be settled
Changelog:
re #27558

webproxy: adds network.target as a requirement for varnish

---

nixos/modules/flyingcircus/packages/fcmanage/fc/manage/manage.py
nixos/modules/flyingcircus/packages/fcmanage/setup.cfg
nixos/modules/flyingcircus/services/fcmanage.nix

Improve maintenance message.
The feature switch has now been migrated to a NixOS configuration
option:
flyingcircus.agent.with-maintenance
The old feature switch /etc/local/build-with-maintenance is now being
ignored.
Re #26699
Impact: Improve "channel activate in maintenance" mode (#26699)
Changelog:

Fix "channel activate in maintenance" mode

---

nixos/modules/flyingcircus/packages/mariadb.nix

Fixes #26901
Impact:
Changelog:
* Security update for MariaDB (https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3302)

Security update for mariadb: 10.0.29 -> 10.0.32

---

pkgs/development/libraries/libxslt/default.nix

Fixes #26902
Impact:
Changelog:
* Security update for libxslt (https://nvd.nist.gov/vuln/detail/CVE-2016-1683 and https://nvd.nist.gov/vuln/detail/CVE-2016-1684)

Security update for libxslt: 1.1.28 -> 1.1.29

---

pkgs/development/interpreters/ruby/rubygems.nix

Fixes #26900
Impact:
Changelog:
* Security update for rubygems (https://nvd.nist.gov/vuln/detail/CVE-2015-3900 and https://nvd.nist.gov/vuln/detail/CVE-2015-4020)

Security update for rubygems: 2.4.1 -> 2.4.8

---

pkgs/development/libraries/libarchive/default.nix

Fixes #23890
Impact:
Changelog:
* Security update for libarchive (https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-2304)

Security update for libarchive: 3.1.2 -> 3.3.2

---

pkgs/development/libraries/libgcrypt/default.nix

Fixes #27181
Impact:
Changelog:
- Apply security update for libcrypt (CVE-2016-6313, https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-6313)

Security update for libgcrypt: 1.6.4 -> 1.6.6

---

nixos/modules/flyingcircus/packages/percona/xtrabackup.nix

to get rid of insecure gstreamer that isn't used otherwise.
Fixes #28030
Impact:
Changelog:
* Remove unused dependency on old gstreamer which has an unfixed vulnerability (https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-9447)

Remove unused xxdiff and thus gstreamer dependency

---

nixos/modules/flyingcircus/roles/nfs.nix

Impact: NFS clients will be restarted on RG share clients. Expect spurious error messages.
Changelog: Downgrade NFS version for RG share clients to work around a hard-to-reproduce NFS bug.
Re #27810

27810 nfs workaround

---

nixos/modules/flyingcircus/packages/postgresql/default.nix

Fixes #28101
Fixes #27463
Impact:
* All PostgreSQL instances will be restarted.
Changelog:
* Security update for PostgreSQL.

Security update PostgreSQL.

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/openssl/default.nix
pkgs/development/libraries/openssl/default.nix

Fixes #27036
Impact:
Changelog:
* Security update for all OpenSSL versions.

Security update for all OpenSSL versions.

---

pkgs/development/interpreters/perl/5.22/default.nix

5.20 never got fixed. Will upgrade with next NixOS version.
Fixes #24076
Impact:
Changelog:
* Security update for Perl 5.22. (https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-1238)

Security update for Perl 5.22.

---

pkgs/servers/sql/mysql/5.5.x.nix

Fixes #24058
Impact:
* Will restart vanilla MySQL 5.5 instances.
Changelog:
* Security update for vanilla MySQL 5.5. (Multiple CVEs)

Security update MySQL 5.5.

---

nixos/modules/flyingcircus/packages/all-packages.nix

Fixes #23877.
Impact:
* (Maybe) restart networking and firewalling and dependent services on NixOS nodes.
Changelog:
* Security update for iptables.

Security update for iptables.

---

pkgs/development/compilers/gcc/4.9/default.nix
pkgs/development/compilers/gcc/5/default.nix

Fixes #23873
Impact:
* Large rebuild of many packages due to the compiler dependency, in turn causing wide-spread service restarts.
Changelog:
* Security update for GCC.

Security update for gcc.

---

nixos/modules/flyingcircus/platform/packages.nix
nixos/modules/flyingcircus/roles/loghost.nix
nixos/modules/flyingcircus/services/graylog.nix

The config script was never started automatically, hence pretty useles. Graylog waits now until it's http port is ready. The config script will be started afterwards.
Impact:
Changelog: Apply initial loghost configuration automatically upon role activation.

Fix graylog configuration activation

---

nixos/modules/flyingcircus/roles/mongodb/default.nix

re #28239
Impact: MongoDB instances will be restarted.
Changelog: Give MongoDBs more time to start up (#28239)

increase mongodb startup time.

---

nixos/modules/flyingcircus/packages/perl-packages.nix
nixos/release-flyingcircus.nix

Some Perl dependencies of LibreOffice need to be updated to reflect a
newer zlib. Additionally, we need to disable some tests as they are
known to be broken (see
https://rt.cpan.org/Public/Bug/Display.html?id=119762).
Re #28259
Impact:
Changelog:

Fix LibreOffice build

---

nixos/modules/flyingcircus/infrastructure/fcio/telegraf.nix

This way multiple outputs of the same kind are possible.
Impact:

outputs are actually lists

---

nixos/modules/flyingcircus/roles/postgresql.nix

Fixes #28247
Impact:
Changelog:
* PostgreSQL: monitor every single listening port to ensure we notice inconsistent states after restarts. (Fixes #28247)

Add explicit port checks for all postgresql listening ports.

---

nixos/modules/flyingcircus/roles/postgresql.nix
nixos/modules/flyingcircus/services/sensu/client.nix
nixos/modules/flyingcircus/services/telegraf.nix
nixos/modules/services/monitoring/collectd.nix

Also fix network dependency for sensu and telegraf.
Add port-based monitoring for PostgreSQL so we notice when it fails to bind
to a required address.
Fixes #28242
Impact:
* PostreSQL will be restarted to activate the changes.
Changelog:
* Ensure correct networking dependencies for PostgreSQL during restarts.
* Add port-based monitoring to ensure PostgreSQL binds to all configured ports.

Ensure correct dependencies for PostgreSQL wrt/ networking.

---

nixos/modules/flyingcircus/services/grafana.nix

re #28290
Impact:
Changelog: Automatically restart Grafana when it crashes. (#28290)

automatically restart grafana

---

nixos/modules/flyingcircus/roles/nginx.nix

reload does a config reload and restarts workers which is not necessary. Also reload will do a config check in near future which could prevent rotating the logs then.
Impact:
Changelog: Do not reload nginx workers during logrotate.

use proper signal for nginx logrotate.

---

nixos/modules/services/web-servers/nginx/default.nix

Also fail properly when configcheck fails.
For necessary restarts (like binary change) see #28206
re #28325
Impact: NGINX will be restarted.
Changelog: Reload NGINX when the configuration changes (instead of restart) #28325

reload nginx instead of restart on config change.

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/roles/haproxy.nix
nixos/modules/flyingcircus/roles/statshost.nix
nixos/modules/flyingcircus/services/prometheus/default.nix

especially set the heap dependent on system memory, updated prometheus for this flag.
retention can be overriden in local.nix
Impact:
Changelog: Update Prometheus to 1.7.1

make prometheus more configurable

---

nixos/modules/services/web-servers/nginx/default.nix

Impact: Nginx will be restarted.
Changelog: To avoid confusion, move the active Nginx configuration to /etc/current-config.

move nginx.config to /etc/current-config (as with haproxy and varnish)

---

nixos/modules/flyingcircus/packages/fcuserscan.nix
nixos/modules/flyingcircus/platform/garbagecollect/default.nix
nixos/modules/flyingcircus/platform/garbagecollect/userscan.exclude

The ZIP lib used is not particularly efficient when it comes to large
archives or archives containing many files. I've excluded JAR and WAR
files as a workaround. In typical Java workflows, those files are
compiled elsewhere and shipped to the target system, so they won't
contain live store references.
In case of local Java code compilation, I'd expect *.class files to
appear. These will be scanned independently.
Re #27553
Impact:
Changelog: -

Exclude JAR and WAR files from userscan

---

nixos/modules/flyingcircus/packages/telegraf/default.nix
nixos/modules/flyingcircus/roles/loghost.nix
nixos/modules/flyingcircus/roles/statshost.nix
nixos/modules/flyingcircus/services/sensu/client.nix
nixos/modules/flyingcircus/services/telegraf.nix

Impact:
* Telegraf will be restarted.
Changelog:
* Enable SNMP for Telegraf. This includes an update to a recent Telegraf bugfix release (1.3.1->1.3.5).

Enable SNMP for Telegraf.

---

nixos/modules/flyingcircus/roles/statshost.nix

This is handy to see targets etc.
Impact:
Changelog: Statshost: Allow direct access to the Prometheus UI.

allow access to prometheus UI via browser

---

nixos/modules/flyingcircus/roles/mysql.nix

This happens in multi-rg/federated setups and yields "sample with repeated timestamp but different value" errors.
Impact:
Changelog: Fix relabelling of MySQL commands metric in federated Prometheus setups.

Only relabel mysql_commands if it was not already relabeled.

---

nixos/modules/flyingcircus/packages/vulnix/default.nix
nixos/modules/flyingcircus/packages/vulnix/requirements_generated.nix
nixos/modules/flyingcircus/packages/vulnix/requirements_override.nix

A newer vulnix version requires has some updated dependencies.
Regenerate pypi2nix dependencies to fix the build.
Re #28663
Impact:
Changelog: Fix error in vulnix deployment #28663

Update dependencies in vulnix deployment re #28663

---

nixos/modules/flyingcircus/packages/php/default.nix

Fixes #28594 (security update for PHP 5.6.30 -> 5.6.31)
Impact:
Changelog:
* Security update for PHP 5.6. (#28594)
* Bugfix updates for PHP 5.6 and 7.0

Update PHP 5.5, 5.6 and 7.0 to most recent bugfix releases.

---

nixos/modules/flyingcircus/packages/ImageMagick/default.nix

Fixes #28605
Impact:
Changelog:
* Security update for ImageMagick: 6.9.9-4 -> 6.9.9-19

Security update ImageMagick: 6.9.9-4 -> 6.9.9-19

---

nixos/modules/flyingcircus/roles/statshost.nix
nixos/modules/flyingcircus/services/prometheus/default.nix

* Federation is not supposed to be used this way (but for aggegation, selection)
* The relay-nodes don't need to write all the data to disk, a simple proxy is just fine.
re #28647
Impact:
Changelog: Stathost: Use NGINX as proxy when using Prometheus to gather metrics in multiple projects (instead of using federation).

Use NGINX as Proxy for Prometheus, instead of using federation.

---

pkgs/servers/varnish/default.nix

Fixes #28593
Impact:
* Varnish will be restarted.
Changelog:
* Security update varnish: 4.0.3 -> 4.0.5 (#28593)

Security update varnish: 4.0.3 -> 4.0.5

---

nixos/modules/flyingcircus/packages/kernel/linux-4.4.nix

This includes a wide variety of stability fixes. Most specifically this fixes
a recurring NFS server crash that we have seen occasionally.
Fixes #28503
Impact:
* Requires a restart of all VMs.
Changelog:
* Update Linux kernel from 4.4.59 -> 4.4.91. (Fixes #28503)

Update NixOS Linux VM kernel: 4.4.59 -> 4.4.91

---

nixos/modules/flyingcircus/packages/curl/default.nix
pkgs/development/libraries/glibc/common.nix

Fixes #27729
Impact:
Changelog:
* Security update for curl: 7.52.1 -> 7.56.0 (#27729)

Security update for curl: 7.52.1 -> 7.56.0

---

pkgs/development/libraries/libxml2/default.nix
pkgs/development/libraries/libxslt/default.nix

libxml: 2.9.4 -> 2.9.6
libxslt: 1.1.29 -> 1.1.31
Fixes #28608
Fixes #28609
Impact:
Changelog:
* Security update for libxml: 2.9.4 -> 2.9.6 (#28608)
* Security update for libxslt: 1.1.29 -> 1.1.31 (#28609)

Security updates for libxml and libxslt.

---

nixos/modules/flyingcircus/services/telegraf.nix

Impact:
Changelog:
* Always restart Telegraf immediately after a crash. This will result in less noise in monitoring and alerting. #28876

Fix #28876: always restart telegraf immediately

---

nixos/modules/flyingcircus/services/clamav.nix

when there's a problem updating.
Fixes #28236
Impact:
Changelog:
* Ignore freshclam's exit status so that the systemd check doesn't alert. #28236

Ignore freshclam's exit status so that the systemd check doesn't alert

---

nixos/modules/flyingcircus/packages/nginx/stable.nix

This PR updates Nginx to latest version of 0.10.x series. 
Impact: Nginx will be restarted

Update Nginx to 0.10.3

---

nixos/modules/flyingcircus/platform/user.nix

Impact:
Changelog: Allow users to run `iotop` via sudo.

Sudo improvements

---

nixos/modules/services/networking/haproxy.nix

Configure service to retry starting haproxy every 5s for 1 min. 
Re #28920
Impact: Service file will be reloaded

Set systemd's retry time for hapoxy to 5s

---

pkgs/applications/version-management/git-and-tools/git/default.nix

Impact:
Changelog:
* Security update for git: 2.7.4 -> 2.14.2. #28729

Security update for git: 2.7.4 -> 2.14.2

---

pkgs/development/libraries/sqlite/default.nix

Fixes #28728
Impact:
* Multiple services may require restarts due to the SQLite library change.
Changelog:
* Security update for SQLite: 3.8.11.1 -> 3.20.1. #28728

Security update for SQLite: 3.8.11.1 -> 3.20.1

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/docsplit/Gemfile
nixos/modules/flyingcircus/packages/docsplit/Gemfile.lock
nixos/modules/flyingcircus/packages/docsplit/default.nix
nixos/modules/flyingcircus/packages/docsplit/gemset.nix
nixos/modules/flyingcircus/packages/docsplit/update.sh
nixos/modules/flyingcircus/tests/default.nix
nixos/modules/flyingcircus/tests/docsplit.nix

Impact:
Changelog: Provide docsplit 0.7.6 package. 
Note: dependencies like libreoffice, pdftk need to be installed separatly via nix-env (or alike)
This is for quaive.

add docsplit 0.7.6

---

nixos/modules/flyingcircus/roles/nginx.nix
nixos/modules/flyingcircus/roles/statshost/default.nix

Impact:
Changelog:  For the loghost-relay, provide a separate access log (``/var/log/nginx/loghost_access.log``), and a separate error log (``/var/log/nginx/loghost_error.log``)

Fix loghost-relay error/access log 

---

nixos/modules/flyingcircus/services/sensu/client.nix

The unit check is mostly meant for units with customer-impact, which this is not. Besides, there is another check on the the stamp file.
Impact:
Changelog: Ignore fc-collect-garbage fails in Sensu monitoring.

Ignore fc-collect-garbage fails in unit check.

---

pkgs/development/interpreters/python/2.7/default.nix

Fixes #28607
Impact:
Changelog:
* Security update for Python 2.7: 2.7.11 -> 2.7.14

Security update for Python 2.7: 2.7.11 -> 2.7.14

---

nixos/modules/flyingcircus/packages/postgresql/default.nix

Impact: This PR updates PostgreSQL 9.4, 9.5 and 9.6 to recent versions of their series fixing a number of bugs. 
(re #29123)
Changelog:
* PostgreSQL servers will be restarted

29123 Update of PostgreSQL

---

nixos/modules/services/web-servers/varnish/default.nix

Impact:
* service file will be reloaded
Changelog:
* varnish service waits for network to be up

Varnish: Depend on network.target to prevent startup errors Re #28908

---

nixos/modules/flyingcircus/tests/default.nix
nixos/modules/flyingcircus/tests/systemd_cycles.nix

This test has been inadvertently deleted from PR #304 while dropping
sysstat completely.
Re #28203
Impact:
Changelog: Test for circular systemd service dependencies (#28203)

Reintroduce circular dependency test

---

nixos/modules/flyingcircus/imaging/vm.nix
nixos/modules/flyingcircus/packages/all-packages.nix
pkgs/build-support/vm/default.nix

bzip2 to lz4 which has been the last insanely slow chunk, but also the
whole copying the store into the VM was extremely slow.
And lastly, fix the reference to the virtualbox guest so it gets correctly
picked upo and ensure it will be also still built on hydra.
Impact:
* This will temporarily break our image charging code as we're moving from bzip2 to lz4 for much faster compression.
Changelog:

Various tunings to massively speed up our VM image. This switches from

---

nixos/modules/flyingcircus/roles/datadog.nix

re #27879
Impact:
Changelog: Don't try to start dogstatsd (from datadog role) when there is no configuration for it (#27879)

don't start dogstatd when there is no config set by user

---

nixos/modules/flyingcircus/packages/python-packages.nix
nixos/modules/flyingcircus/packages/vulnix/default.nix
pkgs/build-support/fetchurl/mirrors.nix

The new vulnix version contains auto-detection of CVE patches. This is
expected to cut false positives significantly.
Also backport `fetchPypi` helper from 17.09.
Impact:
Changelog: Update vulnix to 1.4.0

vulnix: 1.3.4 -> 1.4.0

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/grafana/default.nix

re #29125
Impact:
Changelog: Update to Grafana 4.6.2 (statshost role). This version of Grafana includes annotations, which nicely allow to note events in the dashboards. (#29125)

update to grafana 4.6.2

---

nixos/modules/flyingcircus/lib/utils.nix
nixos/modules/flyingcircus/packages/fcmanage/fc/manage/graylog.py
nixos/modules/flyingcircus/roles/default.nix
nixos/modules/flyingcircus/roles/graylog.nix
nixos/modules/flyingcircus/roles/haproxy.nix
nixos/modules/flyingcircus/roles/loghost.nix
nixos/modules/flyingcircus/tests/default.nix
nixos/modules/flyingcircus/tests/graylog.nix

Impact: Graylog instances will be restarted.
Changelog: 
* Loghosts can be scaled for higher load of messages and better availability, by having multiple Graylog instances, and/or multiple ElasticSearch instances, including MongoDB replication.
* Browser access to graylog is no longer proxied through our self-service portal. A public IP will be needed to access Graylog. Users will user their Flying Cirucs login to directly authenticate against Graylog.
Details: 
* Provide separate graylog role, which only enables graylog, and connects to any ES in the "graylog" cluster.
* Enable LDAP authentication for direct access to graylog, without needing to go through our central proxy
* Setup HAProxy in front of a GELF TCP input. Each graylog node has an HAProxy …

Make loghost scalable

---

nixos/modules/flyingcircus/roles/graylog.nix

Proivde a useful default for graylog's public name

---

nixos/modules/flyingcircus/roles/graylog.nix

Impact:
Changelog: Graylog: Use a sensible HAProxy queue timeout (30s) for the Graylog UI and API.

graylog: Use a sensible queue timeout for haproxy

---

nixos/modules/flyingcircus/platform/packages.nix

Impact: This add htop to our default environment. Most users won't see any difference
Changelog: Add htop to default environment

Add htop to our default environment

---

nixos/modules/flyingcircus/roles/statshost/default.nix

This especially fixes SSL issues with Graylog and Grafana on the same VM.
Impact:
Changelog: Fix SSL for Graylog and Grafana (loghost) on the same VM.

Explicitly bind Grafana to ethfe.

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/nodejs/default.nix
nixos/modules/flyingcircus/tests/default.nix
nixos/modules/flyingcircus/tests/nodejs.nix

nodejs-4.8.5
nodejs-6.11.5
nodejs-8.9.0
re #29513
Impact:
Changelog: 
* Add NodeJS 8.9.0
* Update NodeJS (4.8.5, 6.11.5)

Provide NodeJS8, and update other Versions

---

nixos/modules/flyingcircus/services/prometheus/default.nix

In certain cases the config is rather long. Using echo just fails miserably.
Impact:
Changelog: Allow larger Prometheus configurations.

prometheus: allow longer configuration files

---

nixos/modules/flyingcircus/packages/all-packages.nix

Impact:
Changelog: Update LibreOffice to 5.3.1.2

Update LibreOffice to 5.3.1.2

---

nixos/modules/flyingcircus/roles/statshost/default.nix

Impact:
Changelog: Statshost: Don't create empty relay update script when there are no relays to update (#29308).

29308 stathost fix relayed node update

---

nixos/modules/flyingcircus/packages/clamav.nix

Fixes #28625
Impact:
* ClamAV will be restarted.
Changelog:
* Security update ClamAV: 0.99.2 -> 0.99.3. (#28625)

Security update ClamAV: 0.99.2 -> 0.99.3

---

pkgs/applications/networking/sync/rsync/default.nix

Fixes #29124
Impact:
Changelog:
* Security update rsync: 3.1.2 -> 3.1.3 (#29124)

Security update rsync: 3.1.2 -> 3.1.3

---

nixos/modules/flyingcircus/packages/all-packages.nix

Partially fixes #28596
Impact:
* Many services will be restarted due to the libarchive update which is widely depended upon.
Changelog:
* Update libarchive with additional patches for ongoing CVEs. Partially fixes #28596.

Use updated libarchive version with additional security patches.

---

nixos/modules/flyingcircus/packages/all-packages.nix

Reverts flyingcircusio/nixpkgs#351
Build failure in cmake (dependency via postgis)
https://hydra.flyingcircus.io/build/19614
Re #28596

Revert "Use updated libarchive version with additional security patches."

---

nixos/modules/flyingcircus/packages/all-packages.nix

Fixes #29025
Impact:
Changelog:
* Security update for Subversion: 1.8.15 -> 1.8.19. Fixes #29025

Security update for Subversion: 1.8.15 -> 1.8.19

---

nixos/modules/flyingcircus/packages/all-packages.nix

Fixes #29024
Impact:
Changelog:
* Security update for git: 2.14.2 -> 2.15. Fixes #29024

Security update for git: 2.14.2 -> 2.15

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/openssl/default.nix

Also includes an update to OpenSSH due to aged build script issues.
Fixes #29247
Impact:
* Various services that link against OpenSSL will be restarted.
* OpenSSH servers will be restarted.
* OpenSSH has widely updated their cryptographic policies and disabled various (very) outdated protocols like SSHv1. For details check https://www.openssh.com/releasenotes.html for incompatible changes between version 6.9 and 7.5.
Changelog:
* Security update OpenSSL: -> 1.0.1g, -> 1.0.2n
* Update OpenSSH: 6.9 -> 7.5

Security update OpenSSL: -> 1.0.1g, -> 1.0.2n

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/services/default.nix
nixos/modules/flyingcircus/services/strongswan.nix
nixos/modules/module-list.nix

This PR updates strongSwan to 5.6 and make it installable on our platform. 
Christian removed the strongswan service from nixos/modules/services/networking and placed a copy of the up-to-date version into our overlay. This can be reverted on the next base system update.
Re #29822
Impact:
Changelog: 
* Allow to install strongSwan 5.6

Backport strongSwan 5.6 from 17.09

---

nixos/modules/flyingcircus/services/sensu/api.nix
nixos/modules/flyingcircus/services/sensu/uchiwa.nix

The clients were already using the right settings but the server was running
with an empty username/password pair (and would still allow access with
differing credentials).
Fixes #100173
Impact:
Changelog:
* Fix Sensu API authentication.

Fix Sensu API authentication configuration.

---

nixos/modules/flyingcircus/packages/all-packages.nix

Includes an update for cmake due to compatibility issues.
Fixes #28596.
Impact:
* May restart a number of services depending on libarchive.
Changelog:
* Security update for libarchive 3.3.2 to a selectively patched version.
* Update for cmake due to NixOS 17.09 compatibility issues.

Security update for libarchive 3.3.2 to a selectively patched version.

---

nixos/modules/flyingcircus/packages/all-packages.nix

Reverts flyingcircusio/nixpkgs#360
Leads to build failures in osrm-server and potentially other packages. This seems to be a side effect of a cmake/pkgconfig incompatibility (?). I have seen errors with multiple output/closure size reduction ($lib vs. $out) and possibly a change pkg setup hook in pkgconfig.

Revert "Security update for libarchive 3.3.2 to a selectively patched version."

---

nixos/modules/flyingcircus/services/influxdb011.nix

Impact:
* InfluxDB services will be restarted.
Changelog:
* Configure InfluxDBs' systemd unit to automatically restart after crashes.

Automatically restart crashed InfluxDBs.

---

nixos/modules/flyingcircus/packages/rabbitmq-server.nix
nixos/modules/flyingcircus/roles/rabbitmq.nix
nixos/modules/flyingcircus/services/rabbitmq.nix
nixos/modules/services/amqp/rabbitmq.nix

Impact:
* Restarts all RabbitMQ servers and takes bit of time (~10-15s)  to migrate the on-disk databases.
Changelog:
* Security update for RabbitMQ. #28725

28725 fix rabbitmq update

---

pkgs/development/libraries/libarchive/CVE-2017-14166.patch
pkgs/development/libraries/libarchive/CVE-2017-14502.patch
pkgs/development/libraries/libarchive/default.nix

Impact:
* Many services whose built depends on libarchive may be restarted.
Changelog:
* Update libarchive with patches for CVEs as available.

Update libarchive inline due to multi-output dependency problems.

---

.travis.yml
nixos/modules/flyingcircus/packages/all-packages.nix

Impact:
* Services with dependency on libtiff will be restarted.
Changelog:
* Security update libtiff 4.0.8 -> 4.0.9 with a variety of CVEs. (#29169)

29169 cve libtiff

---

nixos/modules/flyingcircus/roles/nginx.nix

Re #15440
Impact:
Changelog: Switch default nginx logging format to anonymized logs. See https://blog.flyingcircus.io/2018/02/05/new-default-truncated-ip-addresses-in-nginx-access-logs/ for details (#15440).

Switch default to anonymized nginx logs

---

nixos/modules/services/search/elasticsearch.nix

On existing instances there are directories, which we need to remove. They are usually empty. If not, manual intervention will be required.
Case 100722
Impact: 
* ElasticSearch instances will be restarted.
Changelog:
* Fix startup of existing ElasticSearch instances (#100722)

Remove directories where we want to put symlinks.

---

nixos/modules/flyingcircus/platform/firewall.nix

Occasionally there is the error, and the build fails:
syntax error, unexpected $undefined, expecting IND_STR or DOLLAR_CURLY or IND_STRING_CLOSE, at /nix/store/9r68zy1vqkmiix5iccnl3sy4p65r659q-modules/flyingcircus/platform/firewall.nix:16:58
Case 100755
Impact:
Changelog: Fix occasional build error in firewall configuration (#100755)

Fix unquoted $ in multi-line string

---

nixos/modules/flyingcircus/packages/all-packages.nix

Backport Python 3.6

---

nixos/modules/flyingcircus/roles/statshost/default.nix

Fix statshost-proxy nginx logfile names.

---

nixos/modules/flyingcircus/infrastructure/fcio/default.nix

As we do this all the time we've seen that stressed systems may
erroneously decide to power down (this _does_ help to resolve the
stress but we really don't like arbitrary reboots and rather solve
them directly.)
Fixes Case 100612
Impact:
Changelog:

Do not shut down if not reaching the basic target.

---

nixos/modules/flyingcircus/packages/postgresql/default.nix

Impact: 
PostgreSQL-servers will be restarted
Changelog:
* Update Postgres 9.3.18 to 9.3.22
* Update Postgres 9.4.15 to 9.4.17
* Update Postgres 9.5.10 to 9.5.12
* Update Postgres 9.6.6 to 9.6.8
Case 100813

Update Postgres 9.3, 9.4, 9.5 and 9.6 to most recent versions

---

nixos/modules/flyingcircus/packages/all-packages.nix

Case 29164
Changelog:
- Update Ghostscript to 9.22

Use ghostscript from pinned 17.09 release

---

nixos/modules/flyingcircus/roles/postgresql.nix

Bug id: #100204
Impact: PostgreSQL instances will be restarted.
Changelog: Automatically tune PostgreSQL random_page_cost dependent on underlying disk type (HDD/SSD), #100204

Set random_page_cost dependent on underlying disk type

---

pkgs/servers/sql/mysql/5.5.x.nix

Case 101116
Impact: 
* Restart MySQL 5.5 servers
Changelog:
* Update MySQL 5.5 to 5.5.59

MySQL 5.5.57 -> 5.5.59

---

nixos/modules/flyingcircus/roles/rabbitmq.nix

In vagrant there is no ENC, hence the telegraf password could not be calculated. Just use empty string in this case.
Bug Id: 101170
Impact:
Changelog: 
* Fix RabbitMQ role in Vagrant VMs (#101170)

Fix rabbitmq role in vagrant

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/php/default.nix
nixos/modules/flyingcircus/tests/phpzts.nix
nixos/modules/services/web-servers/apache-httpd/default.nix

Impact: The Apache webserver will be restarted.
Changelog:
* Update Apache to 2.4.33
* Update PHP to: 5.6.34, 7.0.28, 7.1.15
* Update Firefox to 59.0.2
* Update qt4 to 4.8.7

101119 update apache php

---

nixos/modules/flyingcircus/roles/redis.nix

Bug id: 101242
Impact:
Changelog: Service users can configure redis via :file:`/etc/local/redis/custom.conf`.

Add hook for services users to configure redis via /etc/local

---

nixos/modules/flyingcircus/packages/all-packages.nix

Fixes #29166
Impact:
Changelog: Security update for libjpeg-turbo: 1.5.3 (CVE-2017-15232, #29166)

libjpeg-turbo: 1.4.1 -> 1.5.3 (CVE-2017-15232)

---

nixos/modules/flyingcircus/infrastructure/vagrant/default.nix

This was we can remove the custom configuration we have in each and every provision.nix.
Bug id: #101293
Impact:
Changelog:
* Add a 2G swapfile for Vagrant boxes (#101293)

Add swapfile for vagrant boxes by default.

---

nixos/modules/flyingcircus/platform/network.nix
nixos/modules/flyingcircus/platform/user.nix
nixos/modules/flyingcircus/roles/haproxy.nix
nixos/modules/flyingcircus/roles/postgresql.nix
nixos/modules/flyingcircus/services/clamav.nix
nixos/modules/flyingcircus/services/kibana.nix
nixos/modules/flyingcircus/services/sensu/client.nix
nixos/modules/flyingcircus/services/telegraf.nix
nixos/modules/services/networking/firewall.nix

Impact:
* Service restarts: PostgreSQL, haproxy, ClamAV, Kibana, Sensu (client), Telegraf
Changelog:
* Improve network dependencies and ordering during boot phase: more robust firewall setup with respect to DNS usage and delayed startup of network-based services.
* Correctly restart PostgreSQL if the ethsrv interfaces are reconfigured to ensure PostgreSQL reopens any lost listening sockets.

Ctheune fix firewall startup

---

nixos/modules/flyingcircus/services/vxlan-client.nix

This is a side effect of recent firewall service changes (PR#408).
Case 101785
Impact:
Changelog: Fix bug in startup ordering of network services (external network routing vs. firewall)

Fix startup ordering for external-network-services

---

nixos/modules/flyingcircus/infrastructure/fcio/telegraf.nix
nixos/modules/flyingcircus/roles/nginx.nix
nixos/modules/flyingcircus/roles/statshost/default.nix
nixos/modules/flyingcircus/roles/statshost/global-relabel.nix
nixos/modules/flyingcircus/tests/default.nix
nixos/modules/flyingcircus/tests/statshost-global.nix
nixos/modules/flyingcircus/tests/statshost-master.nix

* Only the global relay is filtering now.
* There are tests for both cases which can be extended to test futher functionality.
Bug id: #101607
Impact:
Changelog: Fix filtering of metrics for customer-specific statshosts (#101607)

Fix filtering of metrics for customer-specific statshosts.

---

nixos/modules/flyingcircus/roles/loghost.nix

Bugs id #101899
Impact:
Changelog: Update Loghosts to use to ElasticSearch 5 (#101899)

Use ES5 for Loghost

---

nixos/modules/flyingcircus/roles/haproxy.nix
pkgs/tools/networking/haproxy/default.nix

Impact: 
* HAProxy instances will be restarted.
Changelog:
* Update HAProxy 1.5.14 → 1.8.9 (#103210)

103210 update haproxy

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/release-flyingcircus.nix

Bugs id #103319
Impact:
Changelog: 
* Fix building of PHP 5.6 packages, like xcache (#103319)

Fix build of PHP 5.6 packages

---

nixos/modules/flyingcircus/packages/all-packages.nix

Includes:
- #101123 libtiff
- #101837 git
- (no ticket but probably applicable) utillinux
Impact:
Changelog:
- Security update for libtiff (#101123)
- Security update for git (#101837)

Update our 17.09 upstream for security releases: git, libtiff

---

nixos/modules/flyingcircus/packages/openssl/default.nix

Fixes #100885
Impact:
* Restart of many services depending on OpenSSL.
Changelog:
* Security update for OpenSSL: 1.0.2o, 1.1.0h (#100885)

Update OpenSSL: 1.0.2o, 1.1.0h

---

nixos/modules/flyingcircus/packages/curl/default.nix

Fixes #101638
Impact:
Changelog:
- Security update for curl: 7.60.0 (#101638)

Security update curl: 7.60.0

---

nixos/modules/flyingcircus/packages/all-packages.nix

Fixes #101782
Impact:
Changelog:
- Security update for vim: 8.0.1451 (#101782)

Security update for vim: 8.0.1451

---

nixos/modules/flyingcircus/roles/webproxy.nix
nixos/modules/services/web-servers/varnish/default.nix

Goal is to ensure it's tried to be restarted after initial failure where unit entered failed state. This does not address varnish internal errors like VCL-issues
Case 103578

Set varnish-service to restart always 

---

nixos/modules/flyingcircus/packages/postgresql/default.nix

Impact: Will restart PostgreSQL-servers 
Changelog:
* Update PostgreSQL 9.6.8 -> 9.6.9
* Update PostgreSQL 9.5.12 -> 9.5.13 
* Update PostgreSQL 9.4.17 -> 9.4.18
* Update PostgreSQL 9.3.22 -> 9.3.23
* Update PostgreSQL 9.2.15 -> 9.2.24
* Update PostgreSQL 9.1.20 -> 9.1.24 
Case 104680

Update PostgreSQL to most recent versions

---

nixos/modules/flyingcircus/roles/graylog.nix
nixos/modules/flyingcircus/services/graylog.nix

By changing the type of services.graylog.extraConfig from types.str to
types.lines, additional lines can be appended by assigning to this
option in multiple places.
Case 103344
Impact:
Changelog: Allow `services.graylog.extraConfig` to be set from local.nix

Allow graylog.extraConfig lines in local.nix

---

nixos/modules/flyingcircus/packages/all-packages.nix

This package includes also a patch for CVE-2017-14176
Case 101135
Changelog: Update bazaar to 2.7.0

Backport bazaar 2.7.0 from 18.03

---

nixos/modules/flyingcircus/infrastructure/vagrant/default.nix

eth1 becomes ethxfe, because ethfe is not possible due to sorting issues. See comment.
Bugs id: #104769
Impact:
Changelog: 
* Have an ethsrv interface In Vagrant, to closer resemble the live platform.

Configure vagrant so that eth0 becomes ethsrv

---

nixos/modules/flyingcircus/infrastructure/fcio/telegraf.nix
nixos/modules/flyingcircus/lib/network.nix
nixos/modules/flyingcircus/roles/statshost/location-relay.nix

Bugs id: #104851
Impact:
Changelog: To improve stability, configure statshost related firewall settings with IP addresses instead of names (#104851)

Configure statshost firewalls via IPs instead of names

---

nixos/modules/flyingcircus/packages/all-packages.nix

Impact:
* Restart OpenVPN 
Changelog:
* Updates OpenVPN to 2.4.4 (incl. updates of dependencies)
Case 102038

Backport OpenVPN from 18.03

---

nixos/modules/flyingcircus/packages/all-packages.nix

Case 105028
Impact:
* Apache with mod_php enabled will be restarted
Changelog:
* Update PHP 5.6.34 -> 5.6.36
* Update PHP 7.0.28 -> 7.0.30
* Update PHP 7.1.15 -> 7.1.19
* Add PHP 7.2.

105028 Update php to more recent versions

---

pkgs/tools/archivers/sharutils/default.nix

This PR updates sharutils from 4.11.1 to 4.15.2
This includes also a patch against CVE-2018-1000097, but does not necessary address sharutils introduced by e.g. 18.03 import
@flyingcircusio/release-managers e-managers
Impact:
* Rebuild of tools using sharutils e.g. MySQL
Changelog:
* Update sharutils 4.11.1 -> 4.15.2
Case 101089

Update sharutils 4.11.1 -> 4.15.2

---

nixos/modules/flyingcircus/roles/statshost/default.nix

Bugs id #105074
Impact:
Changelog: Give Prometheus more time when shutting down. Before Prometheus was killed after 30s which causes a lengthy crash recovery when starting (#105074)

Give Prometheus more time for shutting down.

---

nixos/modules/services/web-servers/apache-httpd/default.nix

Case 105206
Impact:
* sytemd-unit of Apache will be reloaded
Changelog:
* Prevent Apache from init restarts in case of an error

Set retry time for Apache startup to 1min

---

nixos/modules/flyingcircus/packages/all-packages.nix

Case 105166
This PR ensures we are using Apache as well as PHP from 18.03 branch to avoid issues with mod_php 
Impact:
* Apache will be restarted

Use Apache from 18.03

---

nixos/modules/flyingcircus/platform/network.nix
nixos/modules/flyingcircus/roles/statshost/default.nix

Now rmem_max is generally set to 8M and to 24M on the central statshost.
This is believed to reduce drop outs in telemetry data.
Case 105227
Impact:
Changelog: Reduce drop-outs of telemetry data by enlarging network receive buffers

Increase maximum network receive buffer size

---

pkgs/development/interpreters/ruby/bundix/gemset.nix

Case 105196
This PR updates bundix to 1.0.3 and fixes the used checksum 
Changelog:
* Update bundix to 1.0.2

Update bundix 1.0.2->1.0.3

---

nixos/modules/flyingcircus/packages/curl/default.nix

Impact:
* Restart services linked against libcurl
Changelog:
* Update curl from 7.60 to 7.61.1 
Case 106456

Update curl 7.60 -> 7.61.1

---

nixos/modules/flyingcircus/roles/statshost/location-relay.nix

Nginx proxy was bound to a fixed address (usually ipv4). When a v6 address was chosen to connect to this fails. The proxy_bind is no longer necessary, as the bug in telegraf was fixed quite some time ago. (messed up output for second prometheus output)
bugs id #106553
Impact:
Changelog: Fix metric gaps on central statshost (#106553)

Fix gaps in prometheus metrics on central statshost

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/platform/garbagecollect/default.nix

This PR add an additional import for 18.09 NixOS as well as backports chromium and chromedriver from there
Changelog:
* Backport Chromium 69.0.3497.81 and Chromedriver 2.41 from 18.09
Case 106464
Case 105369

Use Chromedriver and Chromium from 18.09

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/prometheus/default.nix
nixos/modules/flyingcircus/platform/garbagecollect/default.nix
nixos/modules/flyingcircus/roles/statshost/default.nix
nixos/modules/flyingcircus/services/prometheus/default.nix

Impact:
Changelog: 
* Update Prometheus to 2.4.2. Prometheus 1.8 is kept running for about 3 months keep the metrics available (there is no data migration). (#105414).
* Statshost uses InfluxDB for long term storage with downsampled metrics (#105414).

105414 update prometheus downsample influx

---

nixos/modules/flyingcircus/roles/nginx.nix

Logging might fail otherwise if the access_log configuration contains variables.
Bugs id# #106854
Impact:
Changelog:
* Make sure the default nginx docroot exists (#106854)

Make sure the default docroot of nginx is present.

---

nixos/modules/flyingcircus/packages/postgresql/default.nix

Impact:
* Restarts PostgreSQL-servers on NixOS
* Applications linked to libpg might needs re-compiling
Changelog:
* Update PostgreSQL 9.3.24 -> 9.3.25
* Update PostgreSQL 9.4.19 -> 9.4.20
* Update PostgreSQL 9.5.14 -> 9.5.14
* Update PostgreSQL 9.6.10 -> 9.6.11
* Update PostgreSQL 10.6 -> 10.6
Case 107068

Update PostgreSQL to recent versions

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/platform/user.nix
nixos/modules/flyingcircus/roles/default.nix
nixos/modules/flyingcircus/roles/docker.nix
nixos/modules/virtualisation/docker.nix
nixos/release-flyingcircus.nix

Impact:
Changelog:
* Experimental Docker support can now be enabled in NixOS VMs upon request. Service users are able to interact with the Docker daemon. Not intended for production use at the moment.

Add experimental docker support.

---

nixos/modules/flyingcircus/packages/fcmanage/fc/manage/monitor.py

We're seeing spurious outages on v6 that appear to be a provider v6 issue in WHQ.
Impact:
Changelog:

Pin HTTP service checks to v4 only.

---

nixos/modules/flyingcircus/infrastructure/fcio/default.nix

Impact:
Changelog:
* Further reduce swappiness to 10. 
Our platform default is now 10 which is in line with recommendations
"out there" (Red Hat amongst others) as a good setting to maximize
process usage of memory (instead of swapping out) instead of caches.
If users want caches to be used they need to tame their processes first.
From a platform perspective we really do not want to swap out processes
unnecessarily and rather drop VFS.

Lower swappiness even further.

---

nixos/modules/flyingcircus/roles/nginx/default.nix

Impact:
* will restart Nginx on NixOS
Changelog:
* Allow to overwrite map_hash_bucket_size via Nix-expression
Case 107386

Allow to redefine map_hash_bucket_size for Nginx Case 107386

---

nixos/modules/flyingcircus/roles/haproxy.nix

Impact:
* Will reload HAProxy
Changelog:
* Allow to split up configuration files for HAProxy inside /etc/local/haproxy 
Case 107475

Allow to provide multiple config files for HAProxy

---

nixos/modules/flyingcircus/roles/elasticsearch.nix

Impact:
* Reload of unit for ElasticSearch
Changelog:
* Automatic restart ElasticSearch in case of a crash
Case 107568

Always restart ElasticSearch on failure Case 107568

---

nixos/modules/flyingcircus/roles/graylog.nix

Fix wrong generated HAProxy configuration when used in combination with our Graylog-role
Bugfix for Case 107475
Impact:
Changelog:

Fix wrong HAProxy config when used with Graylog

---

nixos/modules/flyingcircus/roles/statshost/default.nix

bugs id: #106554
Impact:
Changelog: 
* Remove Prometheus 1 from stathost VMs. Prometheus 1 was left running to smooth the migration to Prometheus 2 (#106554)

Remove prometheus1 which was left running to migrate to prometheus2

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/fcsensusyntax/Cargo.lock
nixos/modules/flyingcircus/packages/fcsensusyntax/Cargo.toml
nixos/modules/flyingcircus/packages/fcsensusyntax/default.nix
nixos/modules/flyingcircus/packages/fcsensusyntax/src/main.rs
nixos/modules/flyingcircus/packages/rust/default.nix
nixos/modules/flyingcircus/packages/rust/rust-packages.nix
nixos/modules/flyingcircus/services/sensu/client.nix

This check parses all files in /etc/local/sensu-client and reports
syntax errors.
Case 108125
Impact:
Changelog: Monitor syntax and plausibility of user-supplied Sensu checks in `/etc/local/sensu-client` (#108125).

Sensu client syntax check

---

nixos/modules/flyingcircus/packages/graylog/default.nix

Fixes #108321
Impact:
* Graylog instances will be restarted.
Changelog:
* Security update for Graylog: 2.4.5 -> 2.4.6 (#108321)

Security update for graylog: 2.4.5 -> 2.4.6

---

nixos/modules/flyingcircus/packages/all-packages.nix

Fixes #107622
Impact:
Changelog:
* Security update for CUPS: 2.0.4 -> 2.2.6 (#107622)
* Update for GnuPG 2.0 -> 2.2

Security update CUPS 2.0->2.2 (also pulling in gnpug 2.0 -> 2.2)

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/postgresql/temporal_tables/default.nix
nixos/modules/flyingcircus/roles/postgresql.nix
nixos/modules/flyingcircus/tests/postgresql.nix

Impact:
* Will restart PostgreSQL-servers on NixOS
Changelog:
* Add extension extension temporal_tables to default PostgreSQL-installation
Case 108908

Add PostgreSQL extension temporal_tables

---

nixos/modules/flyingcircus/services/sensu/client.nix
nixos/modules/flyingcircus/static/default.nix

Also: fix outdated NTP server entry for DEV.
Impact:
Changelog:
* Use internal NTP servers for health checking to avoid false alerts when using public infrastructure. This is also much better internet citizenship. (#108793)

Do not poll public NTP servers for sensu checking on each machine.

---

nixos/modules/flyingcircus/packages/all-packages.nix
nixos/modules/flyingcircus/packages/redis/default.nix
nixos/modules/flyingcircus/roles/redis.nix
nixos/modules/flyingcircus/services/default.nix
nixos/modules/flyingcircus/services/redis.nix

This PR backports Redis 4.0.11 from current upstream and adds a new role redis4 
Case 108957
Impact:
Changelog:
* Add Redis 4.0.11

Add redis4 role

---

nixos/modules/flyingcircus/services/sensu/client.nix

Fixes Case 107512
Impact:
Changelog:
- Fix Docker compatibility of our disk check. Running a container caused the disk check to fail due to missing permissions. (#107512)

Run the disk check with sudo - otherwise using docker breaks it.

---

pkgs/development/libraries/gettext/CVE-2018-18751.patch
pkgs/development/libraries/gettext/default.nix

Impact:
* Many services will be restarted due to the widespread dependency on gettext.
Changelog:
* Security update for gettext (#107624)

Security update for gettext.

---

nixos/modules/flyingcircus/platform/garbagecollect/default.nix

Using OnActiveSec=2h 30m runs the timer 2 hours and 30 minutes after its activation.
The old setting caused the timer to run 49 minutes after systemd was
started which can trigger the timer shortly after a rebuild. We want to
run it later to avoid high io load.
Impact:
Changelog:
* don't run garbage collection shortly after timer rebuild; increase initial waiting time to 2 hours and 30 minutes

avoid running fc-collect-garbage shortly after timer has been rebuilt

---

nixos/modules/flyingcircus/roles/apache.nix
nixos/modules/flyingcircus/roles/haproxy.nix
nixos/modules/flyingcircus/roles/nginx/default.nix
nixos/modules/flyingcircus/roles/webproxy.nix
nixos/modules/flyingcircus/services/sensu/client.nix

* affects service units that had an after dependency on network.target,
but not network-interfaces.target
* prometheus-node-exporter depends on haproxy now instead of network.target
Impact:
Changelog:
* Avoid service startup errors by starting varnish, haproxy, nginx and httpd after network interfaces

start important network services after network-interfaces

---

nixos/modules/flyingcircus/roles/statshost/default.nix

Impact:
Changelog:
* Fix relay host update timer, the timer's controlled unit was missing a type suffix. (#29649)

Fix unit type for relay hosts

---

nixos/modules/flyingcircus/roles/webdata_blackbee.nix

This doesn't interact well with the VPN setup and matches disabling when external_net is available.
bugs id: #110577
Impact:
Changelog: Update network settings in customer-specific situation (#110577)

disable policy routing for WDS

---

nixos/modules/flyingcircus/roles/external_net/default.nix

bugs id: #100057
Impact:
Changelog: Fix enabling external_net role, when no reverse DNS entry is set (#100057)

Fix external_net role, when no reverse DNS entry is set

---

nixos/modules/flyingcircus/services/sensu/client.nix

* Use buildEnv to combine path contents. The length of the path is limited,
but we want to include more common external dependencies.
* Provide openssl and nix tools (like nix-shell) to Sensu checks.
Impact:
Changelog:
* Provide openssl and nix tools to Sensu checks

Move sensu-client path to an env, add openssl and nix

---

nixos/modules/flyingcircus/roles/webdata_blackbee.nix
nixos/modules/flyingcircus/services/agent.nix
nixos/modules/flyingcircus/tests/default.nix
nixos/modules/flyingcircus/tests/fcmanage.nix

This will reduce unexpected downtimes where our prediction model is missing
critical things that should go without downtime but then causes downtime.
Fixes #110759
Impact:
- No immediate impact. Future updates will cause more maintenance notifications, though.
Changelog:
- Always update production VMs in maintenance windows (in the future). New configs will continue to be built immediately but activation will be scheduled as a maintenance.

Update production VMs in maintenance.

---

nixos/modules/flyingcircus/platform/user.nix

Case 114332
Impact:
Changelog:
* Ensure that a sudo password is always needed for the wheel group (#114332).

Ensure that a sudo password is needed for the wheel group

---

nixos/modules/flyingcircus/services/sensu/client.nix

Case 115283
Changelog
* Allow sensu checks to switch to a service user without password (#115283).

Allow sensuclient to sudo run as a service user

---

nixos/lib/build-vms.nix
nixos/modules/rename.nix
nixos/modules/security/acme.nix
nixos/modules/security/acme.xml
nixos/modules/services/web-servers/nginx/default.nix
nixos/modules/services/web-servers/nginx/vhost-options.nix
nixos/modules/system/activation/switch-to-configuration.pl
nixos/tests/acme.nix
nixos/tests/nesting.nix
pkgs/tools/admin/certbot/default.nix
pkgs/tools/admin/simp_le/default.nix

Impact:
* [NixOS 19.03] Nginx will be reloaded.
Changelog:
* Nginx: fix reload for multiple vhosts with automatic Letsencrypt certificates 
(#115661).
* Nginx: listen address (IPv4 and IPv6) can be configured in JSON vhost config now
(#115661).
* Fixing the reload failures has no new security implications.
* Nginx vhosts defined via JSON config still use the default of binding to all interfaces like before, but it can be limited now with the new option.

Nginx: fix reload/LE problems with vhosts configured via JSON config

---

nixos/modules/flyingcircus/roles/redis.nix

bugs id: #119259
Impact:
Changelog: Remove unecessary lables from Redis metrics (#119259)
No special considerations necessary.

Remove unnecessary labels from redis metrics

---

nixos/modules/flyingcircus/services/rabbitmq.nix
nixos/modules/flyingcircus/tests/rabbitmq.nix

* set Restart=always in unit file
Case 119477
Impact:
* RabbitMQ will be restarted.
Changelog:
* Always restart RabbitMQ (#119477).
None.

Always restart rabbitmq

---

nixos/modules/flyingcircus/infrastructure/fcio/default.nix

Impact:
Changelog:
Admins need to have emergency root ssh keys. I lost the passphrase for my current key, probably when we migrated 1Password to the EU account. I have deleted my old root key (public and private) and generated a new one.
n/a

Update my emergency root ssh key.

---

nixos/modules/flyingcircus/infrastructure/fcio/default.nix
pkgs/tools/misc/grub/2.0x.nix

Use newer grub that (finally and hopefully effectively) fixes XFS's "new" on disk format
compatibility. First tests have shown no regression and actual improvement where
boot time improved and superfluous "invalid xfs node" messages disappeared.
Impact:
Changelog:
* Update grub to 2.04 for improved support of the modern XFS on-disk format and thus reducing reboot times.
No specific requirements, review of changelog did not indicate new/unexpected risks to me as it mostly consists of bugfixes and nothing new related to anything exploitable over the network.
Nothing to test.

update: grub -> 2.04
