nixos/modules/flyingcircus/lib/default.nix, nixos/modules/flyingcircus/platform/default.nix, nixos/modules/flyingcircus/platform/firewall/default.nix
=> Implement local firewall rules.

nixos/modules/flyingcircus/roles/default.nix, nixos/modules/flyingcircus/roles/java.nix
=> Add java role

nixos/modules/flyingcircus/platform/default.nix
=> set timezone as given in ENC

nixos/modules/flyingcircus/roles/mysql.nix
=> 21337 mysql monitoring

nixos/modules/flyingcircus/packages/fcmanage/src/fcmanage/manage.py
10 minutes as a (very?) relaxed initial default.
Fixes #21538
=> Introduce a timeout for the fc-manage job.

nixos/modules/flyingcircus/platform/default.nix
=> disabled password authentication for sshd

nixos/modules/flyingcircus/roles/mailserver.nix, nixos/modules/flyingcircus/services/default.nix, nixos/modules/flyingcircus/services/ssmtp.nix
Configure ssmtp on all nodes of an RG/location if there is one node with the mailout role.
=> Configure ssmtp

nixos/modules/flyingcircus/packages/default.nix, nixos/modules/flyingcircus/packages/mc.nix
=> provide mc package

nixos/modules/flyingcircus/packages/percona/default.nix, nixos/modules/flyingcircus/packages/percona/innotop.nix, nixos/modules/flyingcircus/packages/percona/innotop.patch, nixos/modules/flyingcircus/roles/mysql.nix
=> provide innotop

nixos/modules/flyingcircus/roles/datadog.nix, nixos/modules/flyingcircus/roles/default.nix, nixos/modules/services/monitoring/dd-agent.nix
=> add datadog role

pkgs/servers/http/nginx/default.nix, pkgs/servers/http/nginx/nginx-vuln-1.3.9-1.9.12.patch, pkgs/servers/http/nginx/nginx-vuln-1.9.13-1.11.0.patch, pkgs/servers/http/nginx/unstable.nix
- tested for 1.8.1 (stable) and 1.9.10 (unstable)
re #21775
=> fixes cve-2016-4450 for nginx

nixos/release-flyingcircus.nix
=> build php55 by default

nixos/modules/flyingcircus/platform/default.nix
=> add libjpeg to standard config

nixos/modules/flyingcircus/roles/default.nix, nixos/modules/flyingcircus/roles/varnish.nix, nixos/modules/flyingcircus/roles/webproxy.nix
=> Add varnish (webproxy) role

nixos/modules/flyingcircus/roles/mongodb/default.nix, nixos/modules/flyingcircus/services/sensu/client.nix
=> increase expected connections for mongodb servers

nixos/modules/flyingcircus/platform/logrotate/default.nix
=> enable logrotate for vagrant

nixos/modules/flyingcircus/services/sensu/client.nix
=> Add README.txt to /etc/local/sensu-client explaining what is is about.

nixos/modules/flyingcircus/packages/cron.nix, nixos/modules/flyingcircus/packages/default.nix
=> Improve environment in user crontabs (PATH etc.) #21757 #21964

nixos/release-flyingcircus.nix
=> FC-Release: Make it optional to build image and installer

nixos/modules/flyingcircus/infrastructure/fcio/collectd.nix, nixos/modules/flyingcircus/infrastructure/fcio/default.nix
=> Collect metrics in NixOS VMs (collectd)

nixos/modules/flyingcircus/packages/default.nix, nixos/modules/flyingcircus/packages/osm2pgsql.nix
=> provide osm2pgsql package

.gitignore, nixos/modules/flyingcircus/packages/fcmanage/README.rst, nixos/modules/flyingcircus/packages/fcmanage/fc/manage/manage.py, nixos/modules/flyingcircus/packages/fcmanage/fc/manage/resize.py, nixos/modules/flyingcircus/packages/fcmanage/fc/manage/tests/test_cores.py, nixos/modules/flyingcircus/packages/fcmanage/setup.py, nixos/modules/flyingcircus/packages/fcutil/fc/util/lock.py
=> Reboot VMs automatically when the number of cores is changed (#22200)

nixos/modules/flyingcircus/roles/statshost.nix, nixos/release-flyingcircus.nix
Also, use our "real" nginx role so we get the production ready config.
=> Implement SSL for our stats host.

nixos/modules/flyingcircus/packages/default.nix, nixos/modules/flyingcircus/packages/mongodb/default.nix, nixos/modules/flyingcircus/packages/mongodb/valgrind-include.patch, nixos/release-flyingcircus.nix
Changelog: Add mongodb 3.2.1 (optional, default is still 3.0.x).
=> Add mongodb 3.2.1 package

nixos/modules/flyingcircus/packages/fcsensuplugins/fc/sensuplugins/journal.py
=> Added exception handling for journalctl ret=256

nixos/modules/flyingcircus/platform/packages.nix, nixos/modules/flyingcircus/roles/webproxy.nix, nixos/release-flyingcircus.nix
=> Fix varnish tools defaults so they just work without explicit statedir specification (#22948)

nixos/modules/flyingcircus/lib/files.nix, nixos/modules/flyingcircus/platform/logrotate/default.nix, nixos/modules/flyingcircus/platform/logrotate/user-logrotate.sh, nixos/modules/flyingcircus/platform/systemd.nix, nixos/modules/flyingcircus/roles/haproxy.nix, nixos/modules/flyingcircus/roles/mongodb/default.nix, nixos/modules/flyingcircus/roles/nfs.nix, nixos/modules/flyingcircus/roles/webproxy.nix, nixos/modules/flyingcircus/services/default.nix, nixos/modules/flyingcircus/services/rsyslog.nix, nixos/modules/flyingcircus/services/sensu/server.nix
- haproxy
- mongodb
- sensu server
Re #22535
Re #23015
=> Introduce rsyslog for NixOS VMs and drain several sources of high-volume journal logging to stabilize VM hosts (#22535, #23015)

nixos/modules/flyingcircus/roles/redis.nix
Old haviour was to create a symlink to Nix store storing the password
for redis. In this case only root was able to change the random password
e.g. via editing /etc/nixos/local.nix.
Now a service user can provide a /etc/local/redis/password via e.g.
deployment.
Re #23116
=> Make redis password configurable by service users (#23116)

nixos/modules/flyingcircus/services/sensu/server.nix
This becomes possible by using the HTTP api instead of rabbitmqctl (which is very slow)
Changelog: Automatically monitor new NixOS VMs.
=> Monitor if new NixOS VMs are successfully bootstrapped

nixos/modules/flyingcircus/roles/statshost.nix
=> make postgresql-metrics usable

nixos/modules/flyingcircus/lib/math.nix, nixos/modules/flyingcircus/lib/network.nix, nixos/modules/flyingcircus/platform/network.nix
=> Simplify inter-VM routing (#20617)

nixos/modules/flyingcircus/lib/network.nix, nixos/modules/flyingcircus/packages/default.nix, nixos/modules/flyingcircus/packages/easyrsa/default.nix, nixos/modules/flyingcircus/platform/firewall.nix, nixos/modules/flyingcircus/platform/network.nix, nixos/modules/flyingcircus/roles/default.nix, nixos/modules/flyingcircus/roles/external_net/README.openvpn, nixos/modules/flyingcircus/roles/external_net/default.nix, nixos/modules/flyingcircus/roles/external_net/generate-pki.nix, nixos/modules/flyingcircus/roles/external_net/generate-pki.sh, nixos/modules/flyingcircus/roles/external_net/openvpn.nix, nixos/modules/flyingcircus/static/default.nix, nixos/modules/flyingcircus/vagrant-provision.nix
=> Add "external_net" role which creates a RG-specific OpenVPN gateway (#21387)

nixos/modules/flyingcircus/roles/mongodb/default.nix
re #23454
changelog: Fix MongoDB logrotate rule (#23454)
=> fix mongodb logrotate rule

nixos/modules/flyingcircus/platform/packages.nix, nixos/modules/flyingcircus/roles/mailserver.nix
changelog: Improve Postfix monitoring (#23353)
=> Improve Postfix monitoring: mailq check, port check (#23353)

nixos/modules/flyingcircus/packages/default.nix, nixos/modules/flyingcircus/packages/rabbitmq_delayed_message_exchange.nix, nixos/modules/flyingcircus/packages/rabbitmq_install_plugin.sh, nixos/modules/services/amqp/rabbitmq.nix
changelog: Add delayed message exchange plugin for RabbitMQ (#23617)
=> Make delayed message exchange plugin for RabbitMQ optionally availabe (#23617)

nixos/modules/flyingcircus/packages/fcmanage/fc/manage/manage.py, nixos/modules/flyingcircus/platform/default.nix, nixos/modules/flyingcircus/services/fcmanage.nix
=> Enable `sudo fc-manage --build` for service users as a way to trigger system rebuilds (#23731)

pkgs/tools/networking/chrony/default.nix
=> chronyd: updated to 2.4

pkgs/tools/system/collectd/default.nix
=> collectd: updated to 5.4.3

pkgs/tools/networking/curl/default.nix
=> curl: update to 7.50.3 due to CVE

pkgs/tools/networking/curl/default.nix
Reverts flyingcircusio/nixpkgs#100
=> Revert "curl: update to 7.50.3 due to CVE"

nixos/modules/flyingcircus/packages/default.nix, nixos/modules/flyingcircus/packages/mailx.nix, nixos/modules/flyingcircus/roles/webdata_blackbee.nix
changelog: Add heirloom-mailx package
=> Add mailx package

pkgs/top-level/php-packages.nix
changelog: Add PHP Pecl packages: mongodb and ssh2
=> Zagy add php packages

nixos/modules/flyingcircus/roles/webdata_blackbee.nix
=> Update WDS role from branch

nixos/modules/flyingcircus/packages/vulnix.nix, nixos/modules/flyingcircus/services/sensu/client.nix
=> Update vulnix (#23254)

nixos/modules/flyingcircus/infrastructure/fcio/quota.nix
=> Quota: Added missing systemd-quotacheck.service and quotaon.service (#21808)

nixos/modules/flyingcircus/platform/default.nix, nixos/modules/flyingcircus/platform/firewall.nix, nixos/modules/flyingcircus/platform/user.nix, nixos/modules/flyingcircus/roles/external_net/README.openvpn, nixos/modules/flyingcircus/roles/external_net/README.vxlan, nixos/modules/flyingcircus/roles/external_net/default.nix, nixos/modules/flyingcircus/roles/external_net/openvpn.nix, nixos/modules/flyingcircus/roles/external_net/vxlan.nix, nixos/modules/flyingcircus/services/gateway.nix, nixos/modules/flyingcircus/services/sensu/client.nix, nixos/modules/flyingcircus/services/vxlan-client.nix, nixos/modules/flyingcircus/services/vxlan.nix
Changelog: 
* Allow managed OpenVPN access directly into a resource group (#20617)
* Allow to integrate a VXLAN (Virtual Extensible LAN) into your SRV network (#20617)
=> Add openvpn and vxlan integration (#20617)

nixos/modules/flyingcircus/infrastructure/fcio/quota.nix, nixos/modules/flyingcircus/packages/fcmanage/fc/manage/resize.py
Changelog: Fix quota handling bug which rendered "virtual" disk shrink via quotas effectless (#21994).
Impact: VMs that have exceeded disk quota tacitly may get "disk full" errors.
Re #21994
=> Rework XFS quota handling

nixos/modules/flyingcircus/packages/fcmaintenance/README.rst, nixos/modules/flyingcircus/packages/fcmaintenance/fc/maintenance/activity.py, nixos/modules/flyingcircus/packages/fcmaintenance/fc/maintenance/lib/reboot.py, nixos/modules/flyingcircus/packages/fcmaintenance/fc/maintenance/lib/tests/reboot_test.py, nixos/modules/flyingcircus/packages/fcmaintenance/fc/maintenance/reqmanager.py, nixos/modules/flyingcircus/packages/fcmaintenance/fc/maintenance/request.py, nixos/modules/flyingcircus/packages/fcmaintenance/fc/maintenance/tests/reqmanager_test.py, nixos/modules/flyingcircus/packages/fcmaintenance/fc/maintenance/tests/request_test.py, nixos/modules/flyingcircus/packages/fcmanage/fc/manage/resize.py
Impact:
Changelog: Skip warm reboots if there are cold boots pending (#23965)
=> Skip warm reboots if there are cold boots pending (#23965)

nixos/modules/flyingcircus/infrastructure/fcio/collectd.nix, nixos/modules/flyingcircus/roles/statshost.nix
Impact:
start collecting df metrics into stats.
=> Collectd df metric

nixos/modules/flyingcircus/roles/mysql.nix
Impact: 
Changelog: Actually activate custom mysql configuration in /etc/local/mysql
=> fix local mysql include

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/nodejs6/default.nix, nixos/modules/flyingcircus/packages/nodejs6/setup-hook.sh, pkgs/development/libraries/libuv/default.nix
Impact:
Changelog: Provide nodejs 6.9.1 (#24336)
re #24336
=> provide nodejs6 package

nixos/modules/flyingcircus/platform/packages.nix, nixos/modules/flyingcircus/roles/postgresql.nix, nixos/modules/flyingcircus/tests/postgresql.nix, nixos/modules/flyingcircus/tests/setup.nix, nixos/release-flyingcircus.nix
Impact:
Changelog: Add PostgreSQL 9.5 role (#25215)
=> add postgres95 role

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/collectd.nix, nixos/modules/flyingcircus/packages/collectd/default.nix
- restored 15.09 nix expression of collectd
- moved collectd to n/m/flyingcircus/packages/collectd/
re #23828
Impact:
Changelog:
=> rebased collectd 5.4.3 package

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/curl/WWWCurl-remove-symbol.patch, nixos/modules/flyingcircus/packages/curl/default.nix, nixos/modules/flyingcircus/packages/perl-packages.nix, pkgs/top-level/perl-packages.nix
Impact:
Changelog: - updated to curl 7.52.1 due to several CVEs
(https://curl.haxx.se/docs/vuln-7.47.0.html)
re #23830
=> rebased curl cve against new pkg structure

nixos/modules/flyingcircus/packages/fcmanage/fc/manage/resize.py, nixos/modules/flyingcircus/packages/fcmanage/fc/manage/tests/test_resize.py, nixos/modules/flyingcircus/packages/kernel/linux-4.4.nix
=> selective kernel reboot

nixos/modules/flyingcircus/roles/mongodb/default.nix
Re #24087
Impact:
Changelog: Add mongodb-tools to mongodb servers (#25713)
=> Add mongodb-tools package to mondgodb role

lib/attrsets.nix, lib/strings.nix, nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/kibana.nix, nixos/modules/flyingcircus/services/default.nix, nixos/modules/flyingcircus/services/kibana.nix, nixos/modules/flyingcircus/static/default.nix
Impact:
Changelog: Added Kibana service. 
Note: there is no role, yet, just the plain service. It's in use by WDS with 3 lines of local.nix
=> 25713 kibana

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/rabbitmq-server.nix, nixos/modules/flyingcircus/services/default.nix, nixos/modules/flyingcircus/services/rabbitmq.nix, nixos/modules/flyingcircus/tests/default.nix, nixos/modules/flyingcircus/tests/rabbitmq.nix, nixos/modules/flyingcircus/tests/setup.nix, nixos/modules/services/amqp/rabbitmq.nix, pkgs/servers/amqp/rabbitmq-server/default.nix
Impact: none
Remove changes in upstream in favour of own tree
=> Clean rabbitmq

nixos/modules/flyingcircus/roles/memcached.nix
=> Make memcached listen on all ethsrv-IP

nixos/modules/flyingcircus/roles/elasticsearch.nix
re 25173
Impact:
Changelog: Allow to customize ElasticSearch configuration.
=> allow to customize elasticsearch configuration

nixos/modules/flyingcircus/platform/default.nix, nixos/modules/flyingcircus/roles/loghost.nix, nixos/modules/flyingcircus/services/graylog.nix
- added environment variables regarding location (platform/default.nix)
- added logstash_ssl_import
- fixed correct timezone for graylog
Impact: 
Changelog:
re #22495
=> logstash_ssl_import imports the ssl key from puppet

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/mariadb.nix, nixos/modules/flyingcircus/tests/default.nix, nixos/modules/flyingcircus/tests/mariadb.nix
Impact: - php gets rebuild as well
Changelog: - vulnerabilities up to CVE-2017-3318 fixed
re #23933
=> updated to mariadb-10.0.29, fixed test

nixos/modules/flyingcircus/roles/nginx.nix
re #26021
Impact: NGINX will be restarted.
Changelog: Provide a htaccess file for NGINX to easily authenticate against FCIO users, which are allowed to login to the VM.
Note: we might want to discuss security implications.
=> allow nginx to authenticate against fcio accounts

nixos/modules/flyingcircus/services/sensu/check_journal.yaml
=> add ignores for proftpd failing logins

nixos/modules/flyingcircus/roles/loghost.nix
Impact:
Changelog: Allow token based authentication for Graylog to make the API accessible (#26239).
=> Allow token based authentication for Graylog to make the API accessible (#26239).

nixos/modules/flyingcircus/infrastructure/fcio/collectd.nix
Only use stats proxy, now (if it is available)
Impact: none
=> Remove testwise send of duplicate data. 

nixos/modules/flyingcircus/roles/elasticsearch.nix
Not completely clear how/if the they help. We will tweak them later.
Impact:
Changelog: Add metrics collection for ElasticSearch.
=> add some ES metrics.

nixos/modules/flyingcircus/roles/datadog.nix
When invoked with `dogstatsd start`, dogstatsd daemonizes itself so that
systemd loses control over the process. Change invocation so that
dogstatsd runs in the foreground.
Also change environment so that dogstatsd create its pid file and
pickles in /var/log/datadog. It used to put these files into /tmp where
they had no long life.
Fixes #26538
Impact: 
Changelog: Improve Datadog StatsD service setup (#26538)
=> Remove forking behaviour from dogstatsd

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/electron.nix
Impact:
Changelog:  Add electron 1.6.8
=> add electron 1.6.8

nixos/modules/flyingcircus/platform/default.nix, nixos/modules/flyingcircus/platform/shell.nix
Impact:
Changelog: More informative bash shell prompts: indicate if this is a test or production system.
Re #27045
=> 27045 shellprompt

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/clamav.nix, nixos/modules/flyingcircus/roles/antivirus.nix, nixos/modules/flyingcircus/roles/default.nix, nixos/modules/flyingcircus/services/clamav.nix, nixos/modules/flyingcircus/services/default.nix
Impact:
Changelog: Add basic ClamAV service (#27161)
=> Add basic ClamAV service (#27161)

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/postgis/default.nix, nixos/modules/flyingcircus/packages/postgis/pg_db_postgis_enable.sh, nixos/modules/flyingcircus/packages/postgis/pg_db_postgis_fix_or_load_sql_dump.sh, nixos/modules/flyingcircus/roles/postgresql.nix
re #27361
Impact: PostgreSQL servers will be restarted to add the PostGIS extension.
Changelog:
* Update PostGIS to 2.3.1 (#27361)
* Activate the PostGIS extension automatically for all PostgreSQL servers (#27361)
=> Update postgis and add it automatically to the postgresql role

nixos/modules/flyingcircus/lib/network.nix
The default route is now established via a gateway on the first net for
a given iface/AF combination where a locally configured address exists.
Re #27158
Impact: Network interfaces will be restarted on NixOS VMs in some cases.
Changelog: NixOS: Fix buggy default route creation when multiple networks exist in the same VLAN and some subnets do not have an IP address locally configured (#27158).
=> Fix default routes

.gitignore, nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/fcbox/box/Cargo.lock, nixos/modules/flyingcircus/packages/fcbox/box/Cargo.toml, nixos/modules/flyingcircus/packages/fcbox/box/box.1.rst, nixos/modules/flyingcircus/packages/fcbox/box/src/main.rs, nixos/modules/flyingcircus/packages/fcbox/box/src/test.rs, nixos/modules/flyingcircus/packages/fcbox/default.nix, nixos/modules/flyingcircus/packages/rust/binaryBuild.nix, nixos/modules/flyingcircus/packages/rust/bindgen.nix, nixos/modules/flyingcircus/packages/rust/bootstrap.nix, nixos/modules/flyingcircus/packages/rust/build-support/default.nix, nixos/modules/flyingcircus/packages/rust/build-support/fetch-cargo-deps, nixos/modules/flyingcircus/packages/rust/build-support/fetchcargo.nix, nixos/modules/flyingcircus/packages/rust/build-support/patch-registry-deps/pkg-config, nixos/modules/flyingcircus/packages/rust/rust-packages.nix, nixos/modules/flyingcircus/packages/rust/rustfmt.nix, nixos/modules/flyingcircus/platform/packages.nix
Impact: 
Changelog: Provide `box` client also on NixOS (#21486)
=> 21486 boxclient

nixos/modules/flyingcircus/packages/all-packages.nix
re #27559
Impact:
Changelog: Provide yarn-0.20.3, to be installed via ``nix-env -iA nixos.yarn``
=> provide the yarn package

nixos/modules/flyingcircus/tests/default.nix, nixos/modules/flyingcircus/tests/oraclejava.nix
=> pre-build the dependencies of oracle-java

nixos/modules/flyingcircus/packages/ImageMagick/default.nix, nixos/modules/flyingcircus/packages/all-packages.nix
Impact: rebuilt of sensu, gems
Changelog: update ImageMagick to 6.9.8-10
=> updates ImageMagick due to security reasons

nixos/modules/flyingcircus/packages/fcmanage/fc/manage/graylog.py, nixos/modules/flyingcircus/roles/loghost.nix
(added some additional logging)
Impact:
Changelog: Due to a version update in graylog update a change in graylog-config (api consumer) needed to be done. #27683
=> fixed regression in graylog-config to re-enable the input configuration

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/coturn/default.nix, nixos/modules/flyingcircus/packages/coturn/pure-configure.patch, nixos/modules/flyingcircus/packages/libevent.nix, nixos/modules/flyingcircus/services/coturn.nix, nixos/modules/flyingcircus/services/default.nix, nixos/modules/flyingcircus/static/default.nix
This PR adds basic coturn-service
Re #26679
=> Add coturn service

nixos/modules/flyingcircus/infrastructure/fcio/telegraf.nix, nixos/modules/flyingcircus/roles/mongodb/default.nix, nixos/modules/flyingcircus/roles/mysql.nix, nixos/modules/flyingcircus/roles/nginx.nix, nixos/modules/flyingcircus/roles/postgresql.nix, nixos/modules/flyingcircus/roles/statshost.nix, nixos/modules/flyingcircus/services/telegraf.nix, nixos/modules/flyingcircus/tests/default.nix, nixos/modules/flyingcircus/tests/prometheus.nix
Impact:
Changelog:
(no changelog. Mostly improvements for previous PR.)
=> 27132 grafana prometheus stabilizing

nixos/modules/flyingcircus/packages/ImageMagick/default.nix
Fixes #28031
Impact:
Changelog:
* Security update for imagemagick.
=> Security update for imagemagick.

pkgs/tools/networking/openvpn/default.nix
Fixes #27552.
Impact:
Changelog:
* Security update for OpenVPN.
=> Security update for OpenVPN

pkgs/development/libraries/nettle/default.nix
Fixes #24060
Impact:
Changelog:
* Security update for nettle.
=> Security update for nettle.

pkgs/development/libraries/libsndfile/default.nix
Fixes #23894
Impact:
Changelog:
* Security update for libsndfile.
=> Security update libsndfile.

nixos/modules/flyingcircus/packages/php/default.nix
Fixes #24077
Impact:
Changelog:
* Security update for PHP.
=> Security update for PHP

pkgs/development/libraries/libxml2/default.nix
Fixes #24077
Impact:
Changelog:
* Security update for libxml2.
=> Security update for libxml2

pkgs/development/libraries/zlib/default.nix
Fixes #27182
Impact:
Changelog:
* Security update zlib.
=> Security update zlib.

pkgs/tools/archivers/unzip/CVE-2014-9913.patch, pkgs/tools/archivers/unzip/CVE-2016-9844.patch, pkgs/tools/archivers/unzip/default.nix
Fixes #26968
Impact:
Changelog:
* Security update for unzip.
=> Security update for unzip.

pkgs/development/libraries/jasper/default.nix
Fixes #23878
Impact:
Changelog:
* Security update for Jasper.
=> Security update for Jasper.

nixos/modules/flyingcircus/packages/all-packages.nix
Impact:
Changelog: Provide PHP extensions for PHP 7.0 (#24768)
=> provide php70Packages

nixos/modules/flyingcircus/roles/webproxy.nix
re #24768
Impact:
Changelog: Gather Varnish metrics (#24768)
=> gather varnish metrics

nixos/modules/flyingcircus/infrastructure/fcio/telegraf.nix
Impact: 
Changelog: Custom labels on VMs are used to label Prometheus metrics (#27132)
=> push custom labels via telegraf to prometheus

nixos/modules/flyingcircus/packages/php-packages.nix
Impact:
Changelog: Provide yaml package for PHP.
=> provide yaml for php

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/yarn.nix
re #27873
Impact:
Changelog: Update yarn to 0.27.5 (#27873)
=> update yarn to 0.27.5

nixos/modules/flyingcircus/roles/haproxy.nix, nixos/modules/services/networking/haproxy.nix
Impact: haproxy will be restarted.
Changelog: Reload haproxy when the configuration changes instead of restart (#28325).
=> 28325 reload haproxy

nixos/modules/flyingcircus/roles/webproxy.nix
Impact: Varnish will be restarted.
Changelog: Reload a changed varnish configuration instead of restarting varnish with the new configuration (#28325)
=> 28325 reload varnish

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/osm2pgsql.nix, nixos/modules/flyingcircus/packages/osrm-backend/default.nix, nixos/release-flyingcircus.nix
Impact:
Changelog: 
* Update osrm-backend tp 4.5.0, and update osm2pgsql to 0.92.1 (#28514).
=> 28514 osm update

nixos/modules/flyingcircus/roles/redis.nix
Impact:
Changelog: Collect metrics from Redis.
=> collect metrics from redis

nixos/modules/flyingcircus/roles/statshost.nix
(which was factor 10 too small)
Impact:
Changelog: Fix Prometheus target heap size calulation.
=> fix prometheus heap caluclation

nixos/modules/flyingcircus/roles/statshost.nix
Impact:
Changelog: Statshost: allow metric relabling via /etc/local/statshost/metric-relabel.yaml.
=> allow metric relabling via /etc/local/statshost/metric-relabel.yaml

nixos/modules/flyingcircus/packages/pcre.nix
Fixes #27731
Impact:
Changelog:
* Security update for pcre: 8.40 -> 8.41
=> Security update for pcre: 8.40 -> 8.41

nixos/modules/flyingcircus/services/kibana.nix
Fixes #28795
Impact:
Changelog:
* Always restart Kibana after a crash. #28795
=> Always restart Kibana.

nixos/modules/flyingcircus/packages/fcsensuplugins/fc/sensuplugins/cpu.py, nixos/modules/flyingcircus/packages/fcsensuplugins/setup.py, nixos/modules/flyingcircus/services/sensu/client.nix
Alert at 15% for now.
Fixes #28296.
Impact:
Changelog:
* Monitor steal to ensure we do not miss completely overloaded hosts. #28296
=> Monitor steal to ensure we do not miss completely overloaded hosts.

nixos/modules/flyingcircus/roles/default.nix, nixos/modules/flyingcircus/roles/rabbitmq.nix
This PR adds a role for RabbitMQ
=> Add a very basic RabbitMQ role Re #28707

nixos/modules/flyingcircus/packages/all-packages.nix, pkgs/tools/graphics/wkhtmltopdf/default.nix
re #28838
Impact:
Changelog: Update wkhtmltopdf to 0.12.4 (#28838)
=> update wkhtmltopdf to 0.12.4

nixos/modules/flyingcircus/packages/rabbitmq-server.nix, nixos/modules/flyingcircus/roles/rabbitmq.nix, nixos/modules/flyingcircus/services/rabbitmq.nix, nixos/modules/services/amqp/rabbitmq.nix
Fixes #28725
Impact:
* Requires a RabbitMQ restart.
Changelog:
* Security update for RabbitMQ. (#28725)
=> Security update RabbitMQ.

nixos/modules/flyingcircus/infrastructure/fcio/telegraf.nix
=> relabel netstat metrics to be useful

nixos/modules/flyingcircus/tests/default.nix, nixos/modules/flyingcircus/tests/phpzts.nix
=> add prebuild for php wiht zts

nixos/modules/flyingcircus/roles/mysql.nix
Impact: MySQL will be restarted.
Changelog: none.
=> 28720 readme mysql

nixos/modules/flyingcircus/roles/rabbitmq.nix
Impact:
Changelog: Gather rabbitmq metrics via telegraf (#28950)
=> Gather rabbitmq metrics via telegraf.

nixos/modules/flyingcircus/packages/fcuserscan.nix, nixos/modules/flyingcircus/packages/rust/default.nix, nixos/modules/flyingcircus/packages/rust/print-hashes.sh, nixos/modules/flyingcircus/packages/rust/rust-packages.nix, nixos/modules/flyingcircus/platform/garbagecollect/default.nix
Impact:
Changelog: Limit fc-userscan's memory consumption to avoid out-of-memory conditions (#28934)
=> 28934 userscan limit

nixos/modules/flyingcircus/roles/mailserver.nix
Postfix >=3.0 expects permissions not compatible with the old
setuid-wrapper scheme. This results in an internal setuid-wrapper error
when trying to invoke `sendmail` from an unprivileged users.
Also fix permissions for the ssmtp pseudo-wrapper which seems to suffer
from the same problem.
Re #29181
Impact:
Changelog:
=> Fix sendmail setuid-wrapper permissions re #29181

nixos/modules/flyingcircus/packages/all-packages.nix
This includes updating pkgs_17_09 to a current version.
Re #26909
Impact:
Changelog: Security patches for audiofile 0.3.6 (#26909)
=> Update audiofile from 17.09

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/release-flyingcircus.nix
Impact:
Changelog: Update Firefox to 56.0.2.
=> update firefox (from 17.09) and prebuild it

nixos/modules/flyingcircus/roles/statshost/default.nix
Impact:
Changelog: Decrease Grafana's log-level to INFO
=> decrease grafana's log-level to INFO

nixos/modules/flyingcircus/roles/statshost/README.nix, nixos/modules/flyingcircus/roles/statshost/default.nix
Impact:
Changelog: Stathost: Allow job-specific relabel configuration.
=> Stathost: Allow job-specific relabel configuration

nixos/modules/flyingcircus/roles/graylog.nix, nixos/modules/flyingcircus/roles/mongodb/default.nix
Impact: MongoDB instances will be restarted.
Changelog:
* Update MongoDB configuration file format to YAML (#29483).
* Reduce MongoDB memory usage on Graylog nodes (#29483).
=> Mongodb config update and loghost limit

nixos/modules/flyingcircus/packages/graylog.nix, nixos/modules/flyingcircus/roles/graylog.nix, nixos/modules/flyingcircus/roles/loghost.nix, nixos/modules/flyingcircus/services/graylog.nix
Impact: Graylog instances will be restarted.
Changelog: 
* Update Graylog to 2.4.0
* Provide Slack/Mattermost output plugin for Graylog (#29574)
=> Graylog 2.4.0

nixos/modules/flyingcircus/roles/default.nix, nixos/modules/flyingcircus/roles/kibana.nix, nixos/modules/flyingcircus/tests/default.nix, nixos/modules/flyingcircus/tests/kibana.nix
Impact:
Changelog: Add Role for Kibana (#29588)
=> 29588 kibana role

nixos/modules/flyingcircus/roles/nginx.nix
Re #15440
Impact:
Changelog: Provide "anonymized" and "nonanonymized" log_formats for inclusion in custom nginx.conf snippets.
=> Templates anonymized nginx access.log

nixos/modules/flyingcircus/roles/graylog.nix
Impact:
Changelog: Statshost: Gather metrics from Graylog
=> Gather metrics for graylog

nixos/modules/flyingcircus/packages/fcmanage/fc/manage/manage.py
=> Put out where the /root/nixpgs symlink links to

nixos/modules/flyingcircus/infrastructure/fcio/default.nix
=> Adding cs to root ssh keys

nixos/modules/flyingcircus/infrastructure/fcio/telegraf.nix, nixos/modules/flyingcircus/packages/fcmanage/default.nix, nixos/modules/flyingcircus/packages/fcmanage/fc/manage/graylog.py, nixos/modules/flyingcircus/packages/fcmanage/setup.py, nixos/modules/flyingcircus/roles/graylog.nix
Impact:
Changelog: Collect Graylog's journal age metric (#100350)
=> 100350 graylog journal age metric

nixos/release-flyingcircus.nix
=> Add pdf2svg to list of preBuild packages

nixos/modules/flyingcircus/roles/elasticsearch.nix
Case 100251
Impact: ElasticSearch instances may be restarted.
Changelog: Fix cluster detection for elasticsearch2 and elasticsearch5 roles (#100251)
=> Fix cluster detection for elasticsearch2/elasticsearch5 roles

nixos/modules/flyingcircus/packages/all-packages.nix
Impact:
Changelog:
Add Python 3.5
=> Add Python 3.5

nixos/modules/flyingcircus/packages/all-packages.nix
Impact:
Changelog:
Add python35Packages
=> Add python35Packages

nixos/modules/flyingcircus/roles/graylog.nix
Impact:
Changelog: 
* Tune HAProxy timeout settings for Graylog (#100770)
=> 100770 graylog timeouts

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/mariadb.nix, nixos/modules/flyingcircus/packages/percona/toolkit.nix
Case 100856
Impact:
Changelog: Provide package for percona-toolkit (#100856).
=> Provide package for percona-toolkit

nixos/modules/flyingcircus/roles/statshost/default.nix
We have this structure since a few month, use it here, too.
Case 100858
Impact:
Changelog: Improve Grafana (Stathost) LDAP integration (#100858)
=> Grafana LDAP integration: Filter users with memberOf

nixos/modules/flyingcircus/packages/all-packages.nix
Changelog:
- Security update for libsndfile #28606
=> 28606 Security update for libsndfile.

pkgs/development/libraries/ilmbase/default.nix, pkgs/development/libraries/openexr/default.nix
Case 27184
Changelog:
- Update of openexr to 2.2.1
=> Update ilmbase/openexr 2.2.0 -> 2.2.1

pkgs/development/libraries/libtasn1/default.nix
Case 28885
Impact:
- A huge number of packages will be rebuilded
Changelog:
-  Update libtasn1 to 4.13
=> Update libtasn1 4.8 -> 4.13 

nixos/modules/flyingcircus/packages/all-packages.nix
Changelog:
- Security update jbig2dec 0.11 to 0.14 Case 29167
=> Security update jbig2dec 0.11 to 0.14 Case 29167

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/vulnix/default.nix, nixos/modules/flyingcircus/packages/vulnix/requirements_generated.nix, nixos/modules/flyingcircus/services/sensu/client.nix
Impact:
Changelog:
* Fix bug in `vulnix` which caused an endless loop (#101294).
=> 101294 vulnix endless loop

nixos/modules/system/activation/switch-to-configuration.pl
=> lazy activation

nixos/modules/flyingcircus/static/default.nix
Impact:
Changelog: Reflect changed router addresses in /etc/resolv.conf (#101944)
=> 101944 resolver

nixos/modules/flyingcircus/packages/coturn/default.nix
This PR updates coturn to latest stable release 4.5.0.7
Case 103214
=> Update coturn to 4.5.0.7

nixos/modules/flyingcircus/packages/all-packages.nix
Case 101794
Impact:
Changelog:
* Backport pipenv from 18.03 (10.1.0)
=> Add pipenv 

nixos/modules/flyingcircus/packages/vulnix/default.nix
Impact:
Changelog: Update vulnix to 1.7
=> Update vulnix to 1.7

nixos/modules/flyingcircus/platform/firewall.nix, nixos/modules/flyingcircus/platform/garbagecollect/default.nix, nixos/modules/flyingcircus/tests/default.nix, nixos/modules/flyingcircus/tests/firewall/atomic.nix, nixos/modules/flyingcircus/tests/firewall/rules/dns+customchain, nixos/modules/flyingcircus/tests/firewall/rules/ignore~, nixos/modules/services/networking/firewall.nix
Impact:
Changelog: Improve firewall activation: atomic failure mode, proper DNS lookups, monitoring
Case 103137
Case 101736
Case 100191
Case 104677
=> 103137 atomic firewall

nixos/modules/flyingcircus/roles/apache.nix, nixos/modules/flyingcircus/roles/default.nix, nixos/modules/flyingcircus/tests/apache.nix, nixos/modules/flyingcircus/tests/default.nix
Bugs id: #104976
Impact:
Changelog: Add preliminary role for running Apache HTTPD (#104976)
=> Add role for apache

nixos/modules/flyingcircus/lib/files.nix, nixos/modules/flyingcircus/roles/apache.nix
Impact:
Changelog: Apache: fix loading of custom config files  (#105003)
=> 105003 fix apache config files

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/postgis/default.nix, nixos/modules/flyingcircus/packages/postgresql/default.nix, nixos/modules/flyingcircus/packages/postgresql/rum/default.nix, nixos/modules/flyingcircus/roles/postgresql.nix, nixos/modules/flyingcircus/tests/default.nix
This PR added Postgres10 incl. a basic role Case 105078
Impact:
* PostgreSQL-server will be restarted
* Update of PostGis
* Update of rum
* Some Indiexes might need to be recreated and extensions reinstalled 
Changelog:
* Add PostgreSQL 10.5
* Update PostGis to 2.4
* Update rum to 1.2.1
=> Add postgres10 role

nixos/modules/flyingcircus/packages/postgresql/default.nix
Impact: 
* Restarts PostgreSQL-server
* Restart Apache in case of mod_php et. al is used
Changelog:
* Update PostgreSQL 9.3.23 -> 9.3.24
* Update PostgreSQL 9.4.18 -> 9.4.19
* Update PostgreSQL 9.5.13 -> 9.5.14
* Update PostgreSQL 9.6.9 -> 9.6.10
=> 105031 postgres update

nixos/modules/flyingcircus/packages/clamav.nix, nixos/modules/flyingcircus/tests/clamav.nix, nixos/modules/flyingcircus/tests/default.nix
Impact:
* Restarts ClamAV
Changelog:
* Update ClamAV from 0.99.3 to 0.99.4
Case 100814
=> 100814 update clamav

nixos/modules/flyingcircus/roles/apache.nix
Impact:
* Will restart Apache 
Changelog:
* Add mod_deflate and mod_filter to Apache's default configuration
=> 105086 add mod_deflate and mod_filter to Apache

nixos/modules/flyingcircus/packages/all-packages.nix
bugs id: #105314
Impact:
Changelog: Provide package for Filebeat 6.2.4 (#105314)
=> Create package for filebeat (filebeat6)

nixos/modules/flyingcircus/roles/kibana.nix
bugs id: #105376
Impact:
Changelog:
* Fix initial activation of Kibana role (#105376).
=> fix initial activation of kibana

nixos/modules/flyingcircus/roles/graylog.nix
=> force local password hashing

nixos/modules/flyingcircus/packages/all-packages.nix
This PR imports NodeJS10 from 18.09 
Changelog:
* Add NodeJS 10.9.0
Case 106647
=> Add NodeJS 10

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/roles/elasticsearch.nix, nixos/modules/flyingcircus/services/kibana.nix, nixos/modules/flyingcircus/tests/default.nix, nixos/modules/flyingcircus/tests/elasticsearch.nix, nixos/modules/services/search/elasticsearch.nix
Impact:
Changelog:
* Add support for ElasticSearch 6
* Remove support for ElasticSearch 2
* Update Kibana to 6.3.2
=> 106678 elasticsearch6

nixos/modules/flyingcircus/roles/statshost/default.nix
Impact:
Changelog: 
* Fix downsampling for newly set up statshosts (#106805)
* Fix influxdb startup on statshosts (#106805)
Note: existing statshosts will be migrated manually
=> 106805 fix influx downsampling

nixos/modules/flyingcircus/roles/apache.nix
Impact:
Changelog:
* Allow users to easily configure Apache modules to be loaded (#104977).
=> 104977 apache modules

nixos/modules/flyingcircus/platform/firewall.nix, nixos/modules/services/networking/firewall.nix
Impact:
Changelog: Fix spurious firewall load failures that may occur when rules in /etc/local/firewall contain host names.
=> 105345 firewall

nixos/modules/flyingcircus/lib/default.nix, nixos/modules/flyingcircus/lib/utils.nix, nixos/modules/flyingcircus/packages/nagios-plugins-official-2.x.nix, nixos/modules/flyingcircus/roles/default.nix, nixos/modules/flyingcircus/roles/graylog.nix, nixos/modules/flyingcircus/roles/ldapserver/DB_CONFIG, nixos/modules/flyingcircus/roles/ldapserver/default.nix, nixos/modules/flyingcircus/tests/default.nix, nixos/modules/flyingcircus/tests/ldap.nix, nixos/modules/services/databases/openldap.nix
Impact:
Changelog:
* Add role "ldap" for running an OpenLDAP server (#105204).
=> 105204 openldap

fc-release.sh, nixos/modules/flyingcircus/lib/utils.nix, nixos/modules/flyingcircus/roles/graylog.nix
Impact:
Changelog: Fix bug in graylog default password generation code (#107295)
=> 107295 graylog password

nixos/modules/flyingcircus/infrastructure/fcio/default.nix, nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/platform/default.nix, nixos/modules/flyingcircus/platform/garbagecollect/default.nix, nixos/modules/flyingcircus/roles/kibana.nix, nixos/modules/flyingcircus/tests/default.nix, nixos/modules/flyingcircus/tests/elasticsearch.nix, nixos/modules/flyingcircus/tests/kibana.nix, nixos/modules/flyingcircus/tests/nodejs.nix, nixos/modules/virtualisation/qemu-vm.nix
Impact: Most services will be restarted
Changelog: Update some package versions (see below)
=> 107440 update 17.09 -> 18.03

nixos/modules/services/monitoring/grafana.nix
Impact:
* Grafana unit will be reloaded 
Changelog:
* Ensure Grafana is restarted after failure
Case 107469
=> Restart Grafana on failure Case 107469

nixos/modules/flyingcircus/platform/systemd.nix, nixos/modules/services/monitoring/grafana.nix
This is a follow up to 8ba0fcd51cb
Impact: 
* Reloading of Grafana unit
Changelog:
* Restart Grafana more aggressive 
Case 107469
=> Do always restart Grafana in case of error

nixos/modules/flyingcircus/roles/mailserver.nix
bugs id: #103083
Impact:
Changelog: * Add separate role for mailout (#103083)
=> add separate mailout role

nixos/modules/flyingcircus/roles/mailserver.nix
bugs id: #107962
Impact:
Changelog: 
* Fix relaying mails via a VM with the `mailout` role. (#107962)
=> Fix relaying mails from other VMs via a `mailout` VM.

nixos/modules/flyingcircus/packages/all-packages.nix
=> 101091 update shadow and nodejs

nixos/modules/flyingcircus/roles/webdata_blackbee.nix
bugs id: #110301
Impact:
Changelog: * Customer-specific routing changes (#110301)
=> Add customer-specific routes to other customer infrastructure

nixos/modules/flyingcircus/roles/webdata_blackbee.nix
bugs id: #110579
Impact:
Changelog: Change update behaviour of production VMs in a customer-specific situation (#110579)
=> update production VMs in maintenance-mode

nixos/modules/flyingcircus/roles/webdata_blackbee.nix
bugs id: #110540
Impact:
Changelog: Fix routing setup during boot in a customer-specific situation (#110540)
=> Fix ip adress of router, as lookup doesn't work well during boot.

nixos/modules/flyingcircus/packages/all-packages.nix, nixos/modules/flyingcircus/packages/nagios-plugins-official-2.x.nix, nixos/modules/flyingcircus/packages/percona/8.0.nix, nixos/modules/flyingcircus/packages/percona/innotop.nix, nixos/modules/flyingcircus/packages/percona/xtrabackup.nix, nixos/modules/flyingcircus/roles/mysql.nix, nixos/modules/flyingcircus/services/percona.nix, nixos/modules/flyingcircus/tests/default.nix, nixos/modules/flyingcircus/tests/mysql.nix
* Update innotop to a compatible version
* Update xtrabackup to a compatible version
* Use nagiosPlugins check_mysql instead of some ruby check
Impact:
Changelog:
* Provide Percona 8.0.15-5 database server (via role percona80)
* Update innotop to 1.12.0
* Update xtrabackup to 8.0.5
=> Package percona 8.0

nixos/modules/services/web-servers/nginx/default.nix, nixos/tests/nginx.nix
support for nginx reload, see https://github.com/flyingcircusio/fc-nixos/pull/24
=> 110209 nginx config

nixos/modules/flyingcircus/services/kibana.nix, nixos/modules/flyingcircus/tests/kibana.nix
* set Restart=always in unit file
Case 111013
Impact:
* Kibana will be restarted
Changelog:
* Always restart kibana (#111013).
Nothing new.
=> Always restart kibana
